"""
Emit a reference Python implementation from the formula IR (§8.1).

The generated module depends on ``math`` and ``numpy`` only, so it runs on a
validator's machine with no MAYA installed.

Copyright (c) 2026 Ashutosh Sinha. All rights reserved.
"""

from __future__ import annotations

from typing import Any

from maya.core.errors import ValidationFailed
from maya.formula.ir import iter_nodes, let_order, refs_of, validate_ir

_BIN = {
    "add": "+",
    "sub": "-",
    "mul": "*",
    "div": "/",
    "pow": "**",
    "gt": ">",
    "lt": "<",
    "ge": ">=",
    "le": "<=",
    "eq": "==",
}
_FN = {
    "exp": "np.exp",
    "log": "np.log",
    "sqrt": "np.sqrt",
    "abs": "np.abs",
    "ncdf": "_ncdf",
    "npdf": "_npdf",
}
_RED = {"max": "np.maximum", "min": "np.minimum", "and": "np.logical_and", "or": "np.logical_or"}


def _ident(name: str) -> str:
    return "v_" + name.replace(".", "__")


def py_expr(node: dict[str, Any]) -> str:
    """A Python expression for one node."""
    if "const" in node:
        return repr(float(node["const"]))
    if "ref" in node:
        return _ident(node["ref"])
    if "param" in node:
        return f"params[{node['param']!r}]"
    op, args = node["op"], [py_expr(a) for a in node["args"]]
    if op in _BIN:
        return "(" + f" {_BIN[op]} ".join(args) + ")"
    if op == "neg":
        return f"(-{args[0]})"
    if op in _FN:
        return f"{_FN[op]}({args[0]})"
    if op in _RED:
        out = args[0]
        for a in args[1:]:
            out = f"{_RED[op]}({out}, {a})"
        return out
    if op == "where":
        return f"np.where({args[0]}, {args[1]}, {args[2]})"
    if op == "na":
        return "np.nan"
    raise ValidationFailed(f"no Python rendering for op '{op}'")


_HEADER = '''"""Reference implementation generated by MAYA from the formula IR. Do not edit."""
import math

import numpy as np

_erfc = np.vectorize(math.erfc, otypes=[float])


def _ncdf(x):
    return 0.5 * _erfc(-np.asarray(x, dtype=float) / math.sqrt(2.0))


def _npdf(x):
    x = np.asarray(x, dtype=float)
    return np.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


'''


def to_python(ir: dict[str, Any]) -> str:
    """Source of a module defining ``predict(X: dict, params: dict) -> dict``."""
    return _HEADER + _function(ir, "predict")


def to_python_composite(ir: dict[str, Any], member_irs: dict[str, dict[str, Any]]) -> str:
    """The same for a composite of closed-form members: one function per member, and a
    ``predict`` that runs them as ``maya.formula.evaluate.evaluate_composite`` does —
    members in training order (else declaration order), each seeing the inputs and the
    earlier members' outputs as ``alias.output``, member parameters taken from
    ``alias.name``, then the combine expression over all of it."""
    comp = ir["composite"]
    order = comp.get("train", {}).get("order") or [m["alias"] for m in comp["members"]]
    parts = [_HEADER, _MEMBER_PARAMS]
    for alias in order:
        member = member_irs[alias]
        if "body" not in member:
            raise ValidationFailed(
                f"member '{alias}' is not closed-form; a composite is "
                "re-executable only over closed-form members"
            )
        parts.append(_function(member, _member_fn(alias)) + "\n\n")
    lines = [
        "def predict(X, params):",
        "    env = {k: np.asarray(v, dtype=float) for k, v in X.items()}",
    ]
    for alias in order:
        lines += [
            f"    for _k, _v in {_member_fn(alias)}(env, "
            f"_member_params(params, {alias!r})).items():",
            f"        env[{alias!r} + '.' + _k] = np.asarray(_v, dtype=float)",
        ]
    lines += [f"    {_ident(ref)} = env[{ref!r}]" for ref in sorted(refs_of(comp["combine"]))]
    out = ir["outputs"][0]["name"] if ir.get("outputs") else "y"
    lines.append(f"    return {{{out!r}: np.asarray({py_expr(comp['combine'])}, dtype=float)}}")
    return "".join(parts) + "\n".join(lines) + "\n"


_MEMBER_PARAMS = """def _member_params(params, alias):
    prefix = alias + "."
    return {k[len(prefix):]: v for k, v in params.items() if k.startswith(prefix)}


"""


def _member_fn(alias: str) -> str:
    return "_member_" + "".join(c if c.isalnum() else "_" for c in alias)


def _function(ir: dict[str, Any], name: str) -> str:
    """``def name(X, params)`` for one closed-form IR."""
    if "body" not in ir:
        raise ValidationFailed("only closed-form models have a reference implementation")
    errors = validate_ir(ir)
    if errors:
        raise ValidationFailed("invalid IR", errors=errors)
    lines = [f"def {name}(X, params):"]
    for inp in ir.get("inputs", []):
        name = inp["name"]
        if inp.get("role") == "constant" and "value" in inp:
            lines.append(f"    {_ident(name)} = params.get({name!r}, {inp['value']!r})")
        elif inp.get("role") in ("parameter", "constant"):
            lines.append(f"    {_ident(name)} = params[{name!r}]")
        else:
            lines.append(f"    {_ident(name)} = np.asarray(X[{name!r}], dtype=float)")
    lets = ir.get("lets") or {}
    for name in let_order(lets):
        lines.append(f"    {_ident(name)} = {py_expr(lets[name])}")
    out = ir["outputs"][0]["name"]
    lines.append(f"    return {{{out!r}: {py_expr(ir['body'])}}}")
    return "\n".join(lines) + "\n"


def compile_reference(ir: dict[str, Any]) -> Any:
    """Compile the generated source and return its ``predict`` callable."""
    namespace: dict[str, Any] = {}
    exec(compile(to_python(ir), "<maya-reference>", "exec"), namespace)  # noqa: S102  # nosec B102 - MAYA's own code, generated from a validated IR
    return namespace["predict"]


# ---- the single-function kernel -------------------------------------------------------
# `to_python` emits a module: imports, two module-level helpers, then `predict`. That is the
# right shape for a file a validator runs, and the wrong shape for a kernel somebody pastes
# into a notebook, a spreadsheet macro or somebody else's codebase, where a loose `_ncdf` at
# module scope is a name collision waiting to happen. This emits one function and nothing
# else: its imports and its helpers live inside it, so the whole kernel moves as one object.

_HELPERS = {
    "ncdf": (
        "    def _ncdf(x):\n"
        '        """The standard normal CDF, vectorised over arrays."""\n'
        "        return 0.5 * _erfc(-np.asarray(x, dtype=float) / math.sqrt(2.0))\n"
    ),
    "npdf": (
        "    def _npdf(x):\n"
        '        """The standard normal density, vectorised over arrays."""\n'
        "        x = np.asarray(x, dtype=float)\n"
        "        return np.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)\n"
    ),
}


def ops_used(ir: dict[str, Any]) -> set[str]:
    """Every operator named anywhere in a closed-form IR."""
    trees = [ir.get("body")] + list((ir.get("lets") or {}).values())
    return {n["op"] for t in trees for n in iter_nodes(t) if "op" in n}


def to_python_kernel(ir: dict[str, Any], name: str = "compute") -> str:
    """Source of exactly one function computing this IR's output.

    The function takes ``X`` (a mapping of the feature inputs, scalars or arrays) and
    ``params`` (the parameters and constants) and returns ``{output: value}`` — the same
    contract as the reference module's ``predict``, in one self-contained object. Nothing
    is defined at module scope: ``import`` statements and any helper the formula needs are
    nested inside the function body, where they cost one lookup on the first call and
    nothing after it."""
    if "body" not in ir:
        raise ValidationFailed("only closed-form models have a compute kernel")
    errors = validate_ir(ir)
    if errors:
        raise ValidationFailed("invalid IR", errors=errors)

    out = ir["outputs"][0]["name"]
    features = [i for i in ir.get("inputs", []) if i.get("role", "feature") == "feature"]
    given = [i for i in ir.get("inputs", []) if i.get("role", "feature") != "feature"]
    used = ops_used(ir)
    helpers = [k for k in ("ncdf", "npdf") if k in used]

    lines = [f"def {_ident_fn(name)}(X, params):"]
    lines.append(
        '    """' + f"Compute `{out}`. Generated by MAYA from the formula IR; do not edit."
    )
    lines.append("")
    lines.append(
        "    X       " + (", ".join(i["name"] for i in features) if features else "(no features)")
    )
    lines.append(
        "    params  " + (", ".join(i["name"] for i in given) if given else "(no parameters)")
    )
    lines.append(f"    returns {{{out!r}: value}}, one entry per row of the inputs.")
    lines.append('    """')
    # Only what the formula actually uses: `math` is here for the helpers' constants, and a
    # formula with no normal distribution in it should not import it to say so.
    if helpers:
        lines.append("    import math")
        lines.append("")
    lines.append("    import numpy as np")
    lines.append("")
    if helpers:
        lines.append("    _erfc = np.vectorize(math.erfc, otypes=[float])")
        lines.append("")
        for key in helpers:
            lines.append(_HELPERS[key])
    for inp in ir.get("inputs", []):
        nm = inp["name"]
        if inp.get("role") == "constant" and "value" in inp:
            lines.append(f"    {_ident(nm)} = params.get({nm!r}, {inp['value']!r})")
        elif inp.get("role") in ("parameter", "constant"):
            lines.append(f"    {_ident(nm)} = params[{nm!r}]")
        else:
            lines.append(f"    {_ident(nm)} = np.asarray(X[{nm!r}], dtype=float)")
    lets = ir.get("lets") or {}
    for nm in let_order(lets):
        lines.append(f"    {_ident(nm)} = {py_expr(lets[nm])}")
    lines.append(f"    return {{{out!r}: {py_expr(ir['body'])}}}")
    return "\n".join(lines) + "\n"


def _ident_fn(name: str) -> str:
    """A safe Python function name from whatever the caller asked to call the kernel."""
    cleaned = "".join(c if c.isalnum() or c == "_" else "_" for c in (name or "compute"))
    return cleaned if cleaned and not cleaned[0].isdigit() else "compute_" + cleaned
