"""
Emit a reference Python implementation from the formula IR (§8.1).

The generated module depends on ``math`` and ``numpy`` only, so it runs on a
validator's machine with no MAYA installed.

Copyright (c) 2026 Ashutosh Sinha. All rights reserved.
"""
from __future__ import annotations

from typing import Any

from maya.core.errors import ValidationFailed
from maya.formula.ir import let_order, validate_ir

_BIN = {"add": "+", "sub": "-", "mul": "*", "div": "/", "pow": "**",
        "gt": ">", "lt": "<", "ge": ">=", "le": "<=", "eq": "=="}
_FN = {"exp": "np.exp", "log": "np.log", "sqrt": "np.sqrt", "abs": "np.abs",
       "ncdf": "_ncdf", "npdf": "_npdf"}
_RED = {"max": "np.maximum", "min": "np.minimum", "and": "np.logical_and", "or": "np.logical_or"}


def _ident(name: str) -> str:
    return "v_" + name.replace(".", "__")


def py_expr(node: dict[str, Any]) -> str:
    """A Python expression for one node."""
    if "const" in node:
        return repr(float(node["const"]))
    if "ref" in node:
        return _ident(node["ref"])
    if "param" in node:
        return f"params[{node['param']!r}]"
    op, args = node["op"], [py_expr(a) for a in node["args"]]
    if op in _BIN:
        return "(" + f" {_BIN[op]} ".join(args) + ")"
    if op == "neg":
        return f"(-{args[0]})"
    if op in _FN:
        return f"{_FN[op]}({args[0]})"
    if op in _RED:
        out = args[0]
        for a in args[1:]:
            out = f"{_RED[op]}({out}, {a})"
        return out
    if op == "where":
        return f"np.where({args[0]}, {args[1]}, {args[2]})"
    raise ValidationFailed(f"no Python rendering for op '{op}'")


_HEADER = '''"""Reference implementation generated by MAYA from the formula IR. Do not edit."""
import math

import numpy as np

_erfc = np.vectorize(math.erfc, otypes=[float])


def _ncdf(x):
    return 0.5 * _erfc(-np.asarray(x, dtype=float) / math.sqrt(2.0))


def _npdf(x):
    x = np.asarray(x, dtype=float)
    return np.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


'''


def to_python(ir: dict[str, Any]) -> str:
    """Source of a module defining ``predict(X: dict, params: dict) -> dict``."""
    if "body" not in ir:
        raise ValidationFailed("only closed-form models have a reference implementation")
    errors = validate_ir(ir)
    if errors:
        raise ValidationFailed("invalid IR", errors=errors)
    lines = [_HEADER + "def predict(X, params):"]
    for inp in ir.get("inputs", []):
        name = inp["name"]
        if inp.get("role") in ("parameter", "constant"):
            lines.append(f"    {_ident(name)} = params[{name!r}]")
        else:
            lines.append(f"    {_ident(name)} = np.asarray(X[{name!r}], dtype=float)")
    lets = ir.get("lets") or {}
    for name in let_order(lets):
        lines.append(f"    {_ident(name)} = {py_expr(lets[name])}")
    out = ir["outputs"][0]["name"]
    lines.append(f"    return {{{out!r}: {py_expr(ir['body'])}}}")
    return "\n".join(lines) + "\n"


def compile_reference(ir: dict[str, Any]) -> Any:
    """Compile the generated source and return its ``predict`` callable."""
    namespace: dict[str, Any] = {}
    exec(compile(to_python(ir), "<maya-reference>", "exec"), namespace)  # noqa: S102 - our own generated code
    return namespace["predict"]
