"""
The system design deck, parts 4–6: models, warrants and evidence, and the
platform that governs them — ending with what version 0.3.0 does not build.

Copyright (c) 2026 Ashutosh Sinha. All rights reserved.
Proprietary and confidential. See LICENSE and NOTICE at the repository root.
"""
from __future__ import annotations

MODELS = [
    {"kind": "divider", "num": "4", "title": "Models",
     "sub": "A model is a compute kernel with four faces versioned together: its mathematics, its code, its parameters and its specification document.",
     "points": ["The formula IR", "Code artifacts and the sandbox", "Specification documents",
                "Composite models", "Spreadsheets and vendor models"]},

    {"kind": "split", "kicker": "The formula IR", "title": "Mathematics as a typed expression tree",
     "left": {"head": "Written three ways, stored once",
              "items": [("Parsed", "From a LaTeX-like expression, with errors that name the position."),
                        ("Lifted", "From an uploaded Python function by AST analysis (maya/formula/pylift.py), or from a workbook."),
                        ("Roles", "Every input is a feature, a parameter or a constant; the parameters are what training fills."),
                        ("Declared black box", "Where there is no closed form, the IR records an opaque node with what the model estimates.")]},
     "right": {"head": "And then made to do work",
               "items": [("Rendered", "LaTeX for the specification document."),
                         ("Diffed mathematically", "“The discount factor changed from continuous to simple compounding” (tests/test_formula.py::test_diff_detects_compounding_change)."),
                         ("Executed", "An evaluator, and generated reference code tested equal to it (test_codegen_agrees_with_evaluate)."),
                         ("Hashed", "LaTeX spelling ignored, mathematics not (test_hash_ignores_latex_but_not_math).")]},
     "note": "maya/formula/: ir.py, parse.py, latex.py, evaluate.py, diff.py, codegen.py. A model version is minted when the IR hash, the artifact hash or the input contract changes."},

    {"kind": "table", "kicker": "Code artifacts", "title": "Six rungs, one refusal each, then a declared sandbox tier",
     "rows": [["Rung", "What it checks"],
              ["1  Parse", "The source parses; ruff runs where installed, and whether it ran is recorded"],
              ["2  Entry point", "The declared entry point matches the MayaModel interface"],
              ["3  Import allowlist", "Only numeric and data libraries (numpy, pandas, scipy, scikit-learn, …)"],
              ["4  Static ban", "No filesystem, process, network or dynamic-code use"],
              ["5  Smoke run", "In the sandbox, against a sample"],
              ["6  Determinism probe", "The smoke run twice, outputs compared"]],
     "col_w": [2.4, 9.3],
     "note": "maya/formula/artifact.py, maya/security/sandbox.py. Tier strong on Linux only when a probe child fails to escape a bubblewrap jail with seccomp and a cgroup v2 scope; moderate or minimal otherwise, named on the health page and recorded on every artifact (tests/test_sandbox.py, tests/test_sandbox_linux.py)."},

    {"kind": "bullets", "kicker": "Specification documents", "title": "A LaTeX document per model version, bound to the IR",
     "items": [("Required sections block submission",
                "Purpose, limitations, formulation, assumptions, data, calibration, validation, weaknesses, change log (tests/test_warrants.py::test_model_submission_is_blocked_by_an_incomplete_spec)."),
               ("Formula blocks are bound to the IR",
                "\\mayaformula renders the mathematics from the IR, so the document cannot drift from the implementation."),
               ("True builds with Tectonic, labelled drafts without it",
                "Without Tectonic, MAYA renders a watermarked draft; typeset.require_true_build forbids approval on a draft outside dev (maya/core/typeset.py, tests/test_typeset.py)."),
               ("Air-gapped sites",
                "Tectonic downloads its TeX bundle on first use, so an air-gapped server must be given a cached bundle.")]},

    {"kind": "table", "kicker": "Composite models", "title": "A DAG of member models governed as one model",
     "rows": [["Rule", "In 0.3.0"],
              ["Kinds", "ensemble, pipeline, router, residual, hierarchical"],
              ["One contract", "The union of member contracts; two members wanting one name at different types is refused, naming the attribute"],
              ["One parameter set", "Namespaced by member alias (base.sigma); a member may borrow an approved set, frozen"],
              ["Maturity", "Capped at the lowest member's; the members blocking promotion are named"],
              ["Reproducible", "Per-member seeds derived from one seed; nesting capped at four; cycles refused"],
              ["Evidence", "A bundle re-executes the composite (tests/test_sdk_modes.py::test_a_composite_model_is_re_executed_by_the_bundle_verifier)"]],
     "col_w": [2.4, 9.3],
     "note": "maya/formula/composite.py, maya/formula/evaluate.py; tests/test_formula.py::test_composite_union_maturity_seeds_and_eval. Decision D-8: one parameter set per composite."},

    {"kind": "split", "kicker": "Models that already exist", "title": "Spreadsheets and vendor models, under the same wrapper",
     "left": {"head": "Spreadsheets as models",
              "items": [("Lifted into the IR", "Arithmetic, standard functions, named cells and ranges, VLOOKUP and HLOOKUP over constant tables."),
                        ("Everything else refused by cell", "Never approximated."),
                        ("Checked twice", "Against the workbook's own cached results, and against LibreOffice Calc recalculating headless."),
                        ("Not checked", "Workbooks saved by Microsoft Excel.")]},
     "right": {"head": "Vendor models",
               "items": [("Kind vendor", "A declared input contract and the vendor's name, product, version and documentation."),
                         ("The same review and warrants", "Contract validation, leakage certificate, checksum, sealing."),
                         ("Unverifiable, marked", "The bundle says it cannot re-execute; blind scoring refuses by name."),
                         ("Covenants are the control", "They are the only one available for a black box.")]},
     "note": "maya/formula/xlsx.py (tests/test_spreadsheet.py, tests/test_spreadsheet_libreoffice.py); maya/services/models.py (tests/test_vendor_models.py)."},
]

WARRANTS = [
    {"kind": "divider", "num": "5", "title": "Warrants and evidence",
     "sub": "A warrant is a named, versioned, permissioned licence to compute. The evidence around it is built to survive leaving the building.",
     "points": ["The training warrant and the checksum cycle", "The leakage certificate",
                "Escrowed holdout", "Execution warrants and covenants",
                "Bundles, offline use, custody and licences"]},

    {"kind": "flow", "kicker": "Training warrant", "title": "The checksum cycle that turns paperwork into a control",
     "steps": [("Draw", "An approved model version plus a feature set; the contract is checked, listing every miss"),
               ("Certify", "A signed leakage certificate is issued with the warrant"),
               ("Download", "Train and validation only; who, when and the checksum are recorded"),
               ("Upload", "Parameters are checked against that checksum and the declared bounds"),
               ("Seal", "Approval by policy; referenced objects become undeletable")],
     "box_h": 2.1,
     "items": ["Parameters trained on data that did not match the checksum are flagged unverified_data and cannot be approved without an explicit override.",
               "Proved end to end by tests/test_warrants.py::test_the_checksum_cycle_seal_score_execute_and_bundle and ::test_contract_mismatch_is_refused_listing_every_attribute."]},

    {"kind": "split", "kicker": "Look-ahead", "title": "The leakage certificate and the escrowed holdout",
     "left": {"head": "Leakage certificate",
              "items": [("The rule", "Every row's knowledge time is at or before its event date plus the declared lag."),
                        ("Signed", "Rows examined, violations with examples, and each exception with its justification."),
                        ("Refused", "An unjustified exception, or a non-causal fill without allow_non_causal."),
                        ("Proved", "tests/test_warrants.py::test_leakage_certificate_refuses_late_knowledge.")]},
     "right": {"head": "Escrowed holdout",
               "items": [("The default", "The test partition is materialized, hashed and never downloaded by a developer."),
                         ("Blind scoring", "MAYA scores uploaded parameters against it and returns metrics only."),
                         ("Counted", "Every scoring attempt is numbered on the warrant: twenty attempts against a holdout is overfitting."),
                         ("The one runtime exception", "Decision D-4: MAYA does not run models, except to score.")]},
     "note": "maya/services/warrants.py. The certificate checks rows the resolved frame carries a knowledge time for; a row with none is not examined."},

    {"kind": "table", "kicker": "Execution warrants", "title": "A live instrument, not a perpetual document",
     "rows": [["Control", "Behaviour in 0.3.0"],
              ["Drawn from", "A training warrant and an approved parameter set, or directly from a model with no parameter inputs"],
              ["Environments", "dev, uat, prod, each permitted explicitly"],
              ["Covenants", "input_null_rate, input_range, output_range, max_rows_per_day, staleness_days — a breach suspends the warrant"],
              ["Limits", "max_calls_per_day, max_rows_per_call, max_rows_per_day — these throttle and record overage, they do not suspend"],
              ["Expiry and revocation", "Every consuming call fails closed, naming the covenant or the person to contact"],
              ["Offline use", "Possible, and labelled unattested on the warrant"]],
     "col_w": [2.6, 9.1],
     "note": "maya/services/execution.py; tests/test_security_regressions.py::test_each_covenant and ::test_execution_limits; tests/test_warrants.py::test_execution_limits_throttle_and_record_overage."},

    {"kind": "split", "kicker": "Evidence that leaves the building", "title": "Bundles, custody and licences",
     "left": {"head": "Reproducibility bundle",
              "items": [("Contents", "Warrant, model and IR, reference code, parameters, the feature set pin's data and manifest, certificate, environment and backend set."),
                        ("verify.py", "Needs Python, pyarrow and numpy, nothing from MAYA; recomputes every hash and re-executes the model."),
                        ("One changed byte", "A tampered bundle is refused before anything is read."),
                        ("SC-2 rehearsed", "A warrant aged two years in the fixture is reproduced from its bundle (tests/test_sc2_aged_warrant.py).")]},
     "right": {"head": "Custody and licences",
               "items": [("Hash-chained audit, anchored", "The chain head is signed and appended to a file and an event hourly; RFC 3161 is optional, and the TSA's signature is checked when its CA is configured."),
                         ("Licence algebra", "A derivation inherits the most restrictive of its sources' terms; a breach is refused naming the source and the clause."),
                         ("Proved", "tests/test_custody.py.")]},
     "note": "maya/services/bundle.py, maya/sdk/offline.py, maya/services/custody.py, maya/security/licence.py. An anchor is only as external as the file it is written to."},
]

PLATFORM = [
    {"kind": "divider", "num": "6", "title": "Governance and platform",
     "sub": "Workflow as data, one authorization function, one door to the database, one client library — each held by a gate rather than by review.",
     "points": ["Workflow and workspaces", "Authorization and authentication",
                "Architecture", "Persistence without migrations", "The gate ladder",
                "What 0.3.0 does not build"]},

    {"kind": "split", "kicker": "Workflow", "title": "Policy is data, governed like everything else",
     "left": {"head": "The engine",
              "items": [("One state machine", "draft, in_review, changes_requested, approved, published, deprecated, retired, withdrawn."),
                        ("Edit-time validation", "An unreachable state or an unsatisfiable approval is refused before it is saved."),
                        ("Governed", "A policy edit is versioned, diffed and approved; its YAML round-trips byte-identically."),
                        ("Break-glass", "Loud, permanent, reported; never silent.")]},
     "right": {"head": "Rehearsing a change",
               "items": [("Workspaces", "A copy-on-write branch of the catalog; approval is the merge, and a moved base is a conflict."),
                         ("Shadow replay", "Dependent execution warrants are re-run on the proposed change and the numeric shift is reported."),
                         ("The recorded challenger", "The assistant's memo is attached to the review; it never approves, blocks or edits, and the reviewer records a response.")]},
     "note": "maya/workflow/, maya/services/workspaces.py, maya/assistant/; tests/test_workflow_and_estate.py, tests/test_workflow_matrix.py, tests/test_delegation.py, tests/test_workspaces.py, tests/test_assistant.py."},

    {"kind": "split", "kicker": "Access", "title": "One authorization function, and who you are",
     "left": {"head": "Authorization",
              "items": [("can(principal, action, object)", "Nothing in the UI, API, SDK or CLI bypasses it."),
                        ("Eight roles as a ceiling", "An ACL cannot grant what the role does not permit."),
                        ("ACL order", "Deny wins, then the most specific grant; separation of duties by namespace preset."),
                        ("Grant conditions", "Row filters, column masks and time bounds, applied on every path.")]},
     "right": {"head": "Authentication",
               "items": [("Passwords", "The KDF and its parameters are stored with each hash and rehash upward; lockout after repeated failures."),
                         ("API keys", "Scoped, environment-bound, expiring, revocable."),
                         ("Single sign-on", "OIDC or SAML 2.0, logout in both directions; TOTP and WebAuthn."),
                         ("Principal cache", "A signed-in session's principal is reused for two seconds; a sign-out reaches other processes within that window.")]},
     "note": "maya/security/authz.py, roles.py, conditions.py; maya/services/auth.py, sso.py. SC-7 checked as a full role × action × state matrix (tests/test_authz_matrix.py)."},

    {"kind": "table", "kicker": "Architecture", "title": "A layered modular monolith with its boundaries enforced",
     "rows": [["Rule", "How it holds"],
              ["The UI is an SDK client", "Nothing under maya.web imports anything but maya.sdk; a gate fails the build (tests/test_web.py::test_web_imports_only_the_sdk)"],
              ["One door to the database", "No sqlalchemy import outside maya.persistence (tools/ci/import_boundaries.py)"],
              ["SDK and API in parity", "Every endpoint has an SDK method and every method an endpoint (tools/ci/sdk_parity.py, SC-13)"],
              ["Every table from one macro", "Paginated, searchable, sortable; a crawler refuses any other table (tools/ci/table_contract.py)"],
              ["One startup script", "python run_maya_web.py; several web processes on one node require PostgreSQL"],
              ["Jobs in the database", "SKIP LOCKED on PostgreSQL, an in-process queue on SQLite; idempotent, cancellable, retried"]],
     "col_w": [2.8, 8.9],
     "note": "maya/: core, config, persistence, security, resolution, formula, workflow, storage, services, jobs, assistant, observability, api, sdk, web, cli. maya_delta/ sits beside it with no MAYA domain knowledge."},

    {"kind": "bullets", "kicker": "Persistence", "title": "Two generated schema files, and no migrations",
     "items": [("One typed metadata, two DDL files",
                "maya/persistence/schema/sqlite.sql and postgresql.sql are generated from the SQLAlchemy models; a gate regenerates both and fails on any diff (SC-15)."),
               ("A mismatched database is refused at startup",
                "It is not upgraded in place (tests/test_workflow_and_estate.py::test_schema_mismatch_refuses_to_start)."),
               ("The upgrade path is export, recreate, import",
                "The estate export reads the database as it is, so it works across the schema change that needs it; a column it cannot fill is named."),
               ("SQLite by default, PostgreSQL by configuration, never mixed",
                "The whole suite has run on both; PostgreSQL 16, 17 and 18 so far, not 14 or 15.")]},

    {"kind": "table", "kicker": "The gate ladder", "title": "python tools/ci/gates.py — never a remembered list",
     "rows": [["Stage", "Gates"],
              ["Static (every run)", "ruff; mypy --strict on maya/services; file size; import boundaries; import cycles; public names per module; seam imports; SDK public symbols; version single source; no secrets; table contract; colour contrast; SDK↔API parity; UI↔SDK parity; API snapshot; protocol literals; bandit; schema drift"],
              ["--tests", "The full suite under a 90% line-coverage floor"],
              ["--fallback", "The suite with every Type A seam pinned to its fallback"],
              ["--security", "pip-audit and the sandbox escape tests"],
              ["--bench", "Benchmark regression over 10% needs a note"]],
     "col_w": [2.3, 9.4],
     "note": "Each gate is shown to fail on a planted violation (tests/test_api_and_gates.py, tests/test_gate_ladder.py). The ladder runs locally and in the pre-commit hook; there is no hosted CI, by decision."},

    {"kind": "bullets", "kicker": "What is not built", "title": "Promised, and not delivered by 0.3.0",
     "items": ["SC-14: only Linux is exercised, by decision; the Windows and macOS code paths have never run.",
               "SC-3: 200 users on one node is not met reliably (p95 0.34 s, 0.22 s, 0.43 s against 0.3 s).",
               "SC-9: a new designer publishing a first model in under an hour has not been timed with a real person.",
               "Most §24.3 capacity targets are unmeasured; SC-5 and search were measured on SQLite only.",
               "No external security review; the restore drill has not been performed on a real deployment.",
               "The Claude provider of the assistant is tested against a stub only; SAML back-channel (SOAP) logout is not supported.",
               "A delta source is accepted by the catalog and has no test."],
     "note": "README “Status” and “What's shipped”, and the plan's milestone status notes, state each of these where it was promised."},

    {"kind": "bullets", "kicker": "Where to go next", "title": "Everything on these slides has a source you can open",
     "items": [("Specification, revision 2.3", "docs/MAYA_Requirements_and_Design.md — the authority."),
               ("Plan", "docs/IMPLEMENTATION_PLAN.md — milestones, with what each delivered and did not."),
               ("Measurements", "docs/BENCHMARKS.md, from the unedited results in docs/benchmarks/."),
               ("Decisions and procedures", "docs/adr/ (twenty-eight records) and docs/runbooks/."),
               ("The theory", "docs/research/models-as-parametric-kernels.tex, and the Concepts and Formalism deck."),
               ("Run it", "python run_maya_web.py, then python -m maya.cli feature quick prices.csv.")]},
]

SLIDES = MODELS + WARRANTS + PLATFORM
