"""
The model inventory, exported in the shape a supervisor asks for.

SR 11-7 (US) and the PRA's SS1/23 (UK) both expect a firm to keep a complete inventory of
its models: what each is for, who owns it, how material it is, whether it was validated and
when it is next looked at, what is still open against it and where it is used. MAYA holds
every one of those facts -- the registry, the governance profile, the findings, the reviews,
the warrants and what the monitoring makes of them -- so the inventory is a *reading*, one
row per model, not a spreadsheet somebody maintains beside the system and lets drift.

The two frameworks ask for broadly the same columns under different names, and SS1/23 asks
for a few things SR 11-7 leaves implicit (the tier as the basis for proportionality, and
restrictions on use as a risk mitigant). So the rows are built once, with stable keys, and
each framework is a labelling of them. This is the inventory in an aligned layout; it is
not a regulatory filing template, and the header of every export says so.

Only models the caller may read are exported, and the export says how many were left out,
because an inventory that silently omits what its reader cannot see reads as complete.

Copyright (c) 2026 Ashutosh Sinha. All rights reserved.
"""

from __future__ import annotations

import builtins
import csv
import io
import json
from typing import Any

from maya.core.clock import utcnow
from maya.core.errors import ValidationFailed
from maya.security.authz import Principal
from maya.services import refs

FORMATS = {
    "csv": "text/csv",
    "json": "application/json",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
}

# key: (SR 11-7 label, SS1/23 label). A label of None leaves the column out of that layout.
COLUMNS: dict[str, tuple[str | None, str | None]] = {
    "model_ref": ("Model ID", "Model identifier"),
    "name": ("Model name", "Model name"),
    "namespace": ("Business area", "Business area"),
    "description": ("Purpose", "Purpose and intended use"),
    "use": ("Use category", "Use category"),
    "kind": ("Model type", "Model type"),
    "black_box": ("Vendor or opaque", "Third-party or opaque"),
    "vendor": ("Vendor", "Third-party provider"),
    "owner": ("Model owner", "Model owner"),
    "tier": ("Risk rating", "Model tier"),
    "derived_tier": ("Derived risk rating", "Derived tier"),
    "tier_basis": (None, "Basis of tiering"),
    "tier_override_reason": ("Rating override reason", "Tier override reason"),
    "exposure": ("Exposure", "Exposure"),
    "status": ("Status", "Lifecycle status"),
    "current_version": ("Current version", "Current version"),
    "approved_at": ("Approval date", "Approval date"),
    "approved_by": ("Approved by", "Approved by"),
    "implementation_tested": ("Implementation tested", "Implementation verified"),
    "last_review": ("Last validation / review", "Last independent review"),
    "last_review_outcome": ("Review outcome", "Review outcome"),
    "reviewer": ("Reviewer", "Independent reviewer"),
    "next_review_due": ("Next review due", "Next review due"),
    "review_overdue": ("Review overdue", "Review overdue"),
    "open_findings": ("Open findings", "Open findings"),
    "open_critical_high": ("Open critical/high findings", "Open critical/high findings"),
    "overdue_findings": ("Overdue findings", "Overdue findings"),
    "accepted_risks": ("Accepted risks", "Accepted risks (post-model adjustments)"),
    "live_warrants": ("Deployments (live warrants)", "Live execution warrants"),
    "environments": ("Environments", "Environments"),
    "executions": ("Executions", "Executions"),
    "monitoring": ("Monitoring status", "Ongoing monitoring status"),
    "restrictions": (None, "Restrictions on use"),
}
FRAMEWORKS = {"sr11-7": 0, "ss1-23": 1, "maya": None}
TITLES = {
    "sr11-7": "Model inventory, SR 11-7 layout",
    "ss1-23": "Model inventory, SS1/23 layout",
    "maya": "Model inventory",
}
NOTICE = (
    "Generated by MAYA from its registry, governance, findings, reviews, warrants and "
    "monitoring records. The column layout is aligned with the named framework; it is not "
    "a regulatory submission template."
)


class InventoryService:
    def __init__(self, platform: Any) -> None:
        self.p = platform

    def rows(self, p: Principal) -> tuple[builtins.list[dict[str, Any]], int]:
        """One row per model the caller may read, and how many were left out."""
        gov = self.p.governance
        out, hidden = [], 0
        health = self._health(p)
        with self.p.uow() as uow:
            for model in uow.repo("models").list(order_by=["name"]):
                if not self.p.access.allowed(uow, p, "read", "model", model):
                    hidden += 1
                    continue
                ns = uow.repo("namespaces").get(model["namespace_id"])
                prof = gov._profile(uow, model)
                versions = uow.repo("model_versions").list(
                    model_id=model["id"], order_by=["-version_no"]
                )
                approved = [v for v in versions if v.get("approved_at")]
                current = approved[0] if approved else (versions[0] if versions else {})
                findings = uow.repo("findings").list(model_id=model["id"])
                live = [f for f in findings if f["state"] in ("open", "remediating", "remediated")]
                today = utcnow().date()
                reviews = uow.repo("model_reviews").list(
                    model_id=model["id"], order_by=["-created_at"], limit=1
                )
                warrants = gov._warrants(uow, model["id"])
                statuses = {w["id"]: self.p.execution.status(w) for w in warrants}
                live_w = [w for w in warrants if statuses[w["id"]] == "live"]
                suspended = [w for w in warrants if statuses[w["id"]] == "suspended"]
                vendor = model.get("vendor") or {}
                grades = [health[w["id"]] for w in warrants if w["id"] in health]
                out.append(
                    {
                        "model_ref": refs.object_ref("model", ns["name"], model["name"]),
                        "name": model["name"],
                        "namespace": ns["name"],
                        "description": model.get("description") or "",
                        "use": (prof["use"] or "not declared").replace("_", " "),
                        "kind": model["kind"],
                        "black_box": "yes" if any(v.get("opaque") for v in versions) else "no",
                        "vendor": " ".join(
                            str(vendor[k]) for k in ("name", "product", "version") if vendor.get(k)
                        ),
                        "owner": gov._owner(uow, model) or "",
                        "tier": prof["tier"],
                        "derived_tier": prof["derived_tier"],
                        "tier_basis": "; ".join(
                            f"{d['driver']}: {d['value']}" for d in prof["drivers"]
                        ),
                        "tier_override_reason": prof["override_reason"] or "",
                        "exposure": prof["exposure"],
                        "status": current.get("state", model.get("status", "")),
                        "current_version": current.get("version_no"),
                        "approved_at": current.get("approved_at"),
                        "approved_by": current.get("approved_by") or "",
                        "implementation_tested": self._tested(current),
                        "last_review": prof["last_reviewed_at"],
                        "last_review_outcome": reviews[0]["outcome"].replace("_", " ")
                        if reviews
                        else "never reviewed",
                        "reviewer": prof["last_reviewed_by"] or "",
                        "next_review_due": prof["next_review_due"],
                        "review_overdue": "yes" if prof["review_overdue"] else "no",
                        "open_findings": len(live),
                        "open_critical_high": sum(
                            f["severity"] in ("critical", "high") for f in live
                        ),
                        "overdue_findings": sum(
                            bool(f["due_date"] and f["due_date"] < today) for f in live
                        ),
                        "accepted_risks": sum(f["state"] == "accepted" for f in findings),
                        "live_warrants": len(live_w),
                        "environments": ", ".join(
                            sorted({e for w in live_w for e in w["spec"].get("environments", [])})
                        ),
                        "executions": sum(int(w.get("executions") or 0) for w in warrants),
                        "monitoring": (
                            "breach"
                            if "breach" in grades
                            else "watch"
                            if "watch" in grades
                            else "ok"
                            if grades
                            else "not deployed"
                        ),
                        "restrictions": "; ".join(
                            f"{w['name']} suspended: {w.get('suspend_reason')}" for w in suspended
                        ),
                    }
                )
            llm_rows, llm_hidden = self._llm_rows(uow, p)
        return out + llm_rows, hidden + llm_hidden

    def _llm_rows(self, uow: Any, p: Principal) -> tuple[builtins.list[dict[str, Any]], int]:
        """LLM applications as inventory rows. Fields that belong to the model governance
        records -- tier, findings, periodic review -- are left blank rather than invented:
        those records are kept for models, and an application's evidence is its evaluations."""
        rows, hidden = [], 0
        blank = dict.fromkeys(COLUMNS, "")
        for app in uow.repo("llm_apps").list(order_by=["name"]):
            if not self.p.access.allowed(uow, p, "read", "model", app):
                hidden += 1
                continue
            ns = uow.repo("namespaces").get(app["namespace_id"])
            versions = uow.repo("llm_app_versions").list(app_id=app["id"], order_by=["-version_no"])
            approved = next((v for v in versions if v["state"] == "approved"), None)
            current = approved or (versions[0] if versions else {})
            evidence = self.p.llm._evidence(uow, current) if current and current.get("id") else None
            owner = uow.repo("users").get(app["owner_id"])
            rows.append(
                {
                    **blank,
                    "model_ref": f"maya://llm/{ns['name']}/{app['name']}",
                    "name": app["name"],
                    "namespace": ns["name"],
                    "description": app.get("description") or app.get("use_case") or "",
                    "use": app.get("use_case") or "",
                    "kind": "llm application",
                    "black_box": "yes",
                    "vendor": f"{current.get('provider', '')} {current.get('model', '')}".strip(),
                    "owner": owner["username"] if owner else "",
                    "tier": None,
                    "derived_tier": None,
                    "exposure": None,
                    "status": current.get("state", "no version"),
                    "current_version": current.get("version_no"),
                    "approved_at": current.get("decided_at") if approved else None,
                    "approved_by": (current.get("decided_by") or "") if approved else "",
                    "implementation_tested": (
                        f"evaluated: {evidence['passed']}/{evidence['cases']} cases passed "
                        f"({evidence['mode']})"
                        if evidence
                        else "no qualifying evaluation"
                    ),
                    "last_review": None,
                    "next_review_due": None,
                    "open_findings": None,
                    "open_critical_high": None,
                    "overdue_findings": None,
                    "accepted_risks": None,
                    "live_warrants": None,
                    "executions": None,
                    "monitoring": "not monitored by MAYA",
                }
            )
        return rows, hidden

    def _health(self, p: Principal) -> dict[str, str]:
        rows = self.p.monitoring.overview(p)["warrants"]
        return {r["id"]: r["health"] for r in rows}

    @staticmethod
    def _tested(v: dict[str, Any]) -> str:
        """What evidence says the implementation computes the model."""
        report = v.get("artifact_report") or {}
        if not v:
            return ""
        if (v.get("formula_ir") or {}).get("body") and not v.get("artifact_hash"):
            return "reference implementation generated from the formula"
        if report.get("passed"):
            conf = report.get("conformance") or {}
            if conf:
                return "artifact validated; conformance " + (
                    "passed" if conf.get("passed") else "FAILED"
                )
            return "artifact validated"
        if v.get("artifact_hash"):
            return "artifact did not pass validation"
        return "no implementation evidence"

    def export(self, p: Principal, fmt: str = "csv", framework: str = "sr11-7") -> dict[str, Any]:
        """The inventory as a file: ``{data, filename, content_type}``."""
        if fmt not in FORMATS:
            raise ValidationFailed(f"format is one of {', '.join(FORMATS)}")
        if framework not in FRAMEWORKS:
            raise ValidationFailed(f"framework is one of {', '.join(FRAMEWORKS)}")
        rows, hidden = self.rows(p)
        col = FRAMEWORKS[framework]
        keys = [k for k, labels in COLUMNS.items() if col is None or labels[col]]
        labels = [k if col is None else COLUMNS[k][col] or k for k in keys]
        stamp = utcnow()
        meta = {
            "title": TITLES[framework],
            "framework": framework,
            "generated_at": stamp.isoformat(timespec="seconds"),
            "generated_by": p.username,
            "models": len(rows),
            "not_shown": hidden,
            "notice": NOTICE,
        }
        if fmt == "json":
            data = json.dumps(
                {**meta, "columns": dict(zip(keys, labels)), "rows": rows}, default=str, indent=2
            ).encode()
        elif fmt == "csv":
            buf = io.StringIO()
            writer = csv.writer(buf)
            writer.writerow([f"# {meta['title']}; {NOTICE}"])
            writer.writerow(
                [
                    f"# generated {meta['generated_at']} by {p.username}; {len(rows)} model(s)"
                    + (f"; {hidden} not shown to this user" if hidden else "")
                ]
            )
            writer.writerow(labels)
            for r in rows:
                writer.writerow(["" if r[k] is None else r[k] for k in keys])
            data = buf.getvalue().encode("utf-8")
        else:
            data = self._xlsx(meta, keys, labels, rows)
        name = f"maya-inventory-{framework}-{stamp:%Y%m%d}.{fmt}"
        with self.p.uow(p.username) as uow:
            uow.audit(
                "inventory.exported",
                object_type="inventory",
                object_ref=framework,
                detail={"format": fmt, "models": len(rows), "not_shown": hidden},
            )
        return {"data": data, "filename": name, "content_type": FORMATS[fmt]}

    @staticmethod
    def _xlsx(
        meta: dict[str, Any],
        keys: builtins.list[str],
        labels: builtins.list[str],
        rows: builtins.list[dict[str, Any]],
    ) -> bytes:
        from maya.formula.xlsx import write_workbook

        def letter(n: int) -> str:
            out = ""
            while n:
                n, rem = divmod(n - 1, 26)
                out = chr(65 + rem) + out
            return out

        widths = {
            letter(i): min(max([len(str(label))] + [len(str(r[k] or "")) for r in rows] + [10]), 60)
            for i, (k, label) in enumerate(zip(keys, labels), start=1)
        }
        about = [
            [k.replace("_", " "), meta[k]]
            for k in ("title", "framework", "generated_at", "generated_by", "models", "not_shown")
        ]
        return write_workbook(
            [
                {
                    "title": "Inventory",
                    "rows": [labels] + [[r[k] for k in keys] for r in rows],
                    "header": True,
                    "freeze": "B2",
                    "widths": widths,
                },
                {
                    "title": "About",
                    "rows": about + [["times", "UTC"], ["notice", NOTICE]],
                    "widths": {"A": 16, "B": 100},
                },
            ]
        )
