"""
The decks, checked by the same tool that claims to check them.

``tools/deck/GUIDE.md`` makes the geometry audit the shipping gate for a deck. A
gate that is wired into no test is a gate somebody forgets, so each deck in
``docs/`` is audited here, its slide count is asserted (a deck module that
silently lost slides still builds), and its document properties are checked to
name the author and nothing else.

Copyright (c) 2026 Ashutosh Sinha. All rights reserved.
"""

from __future__ import annotations

import pathlib
import subprocess
import sys

import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
AUDIT = ROOT / "tools" / "deck" / "audit.py"

DECKS = [
    ("MAYA-Executive-Briefing", 18),
    ("MAYA-System-Design", 41),
    ("MAYA-Capabilities", 37),
    ("MAYA-Concepts-and-Formalism", 31),
]
# Anywhere in the file: no tool or assistant credited as a maker of the deck.
FORBIDDEN = (
    "python-pptx",
    "generated by",
    "generated using",
    "generated with",
    "co-authored",
    "anthropic",
)
# In the document properties, which describe the file itself, stricter still.
FORBIDDEN_IN_PROPERTIES = FORBIDDEN + ("generated", "claude")


def _deck(name: str):
    pptx = pytest.importorskip("pptx")
    return pptx.Presentation(str(ROOT / "docs" / f"{name}.pptx"))


@pytest.mark.parametrize("deck,slides", DECKS, ids=[d for d, _ in DECKS])
def test_the_deck_has_no_geometry_issues(deck, slides):
    pytest.importorskip("pptx")
    result = subprocess.run(
        [sys.executable, str(AUDIT), str(ROOT / "docs" / f"{deck}.pptx")],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert "no geometry issues detected" in result.stdout, (
        f"{deck}.pptx:\n{result.stdout}{result.stderr}\n"
        "Rebuild with tools/deck/build.py and fix the slide the report names."
    )


@pytest.mark.parametrize("deck,slides", DECKS, ids=[d for d, _ in DECKS])
def test_the_deck_has_the_slides_the_guide_claims(deck, slides):
    assert len(_deck(deck).slides) == slides


@pytest.mark.parametrize("deck,slides", DECKS, ids=[d for d, _ in DECKS])
def test_the_deck_names_its_author_and_no_tool(deck, slides):
    prs = _deck(deck)
    props = prs.core_properties
    assert props.author == "Ashutosh Sinha" and props.last_modified_by == "Ashutosh Sinha"
    fields = [props.title, props.subject, props.comments, props.keywords, props.category]
    text = " ".join(f or "" for f in fields)
    assert not [w for w in FORBIDDEN_IN_PROPERTIES if w in text.lower()]
    for slide in prs.slides:
        for shape in slide.shapes:
            if shape.has_text_frame:
                text += " " + shape.text_frame.text
            if getattr(shape, "has_table", False):
                text += " " + " ".join(c.text for r in shape.table.rows for c in r.cells)
    lowered = text.lower()
    assert not [w for w in FORBIDDEN if w in lowered]


def test_the_audit_can_see_tables_at_all():
    """A guard on the gate: an audit that skipped graphic frames would pass a deck
    full of collisions, which is what the previous build's audit once did."""
    source = AUDIT.read_text(encoding="utf-8")
    assert "has_table" in source
    assert "table_height" in source
    assert "is_opaque" in source
