-- ==========================================================================
-- MAYA — PostgreSQL schema
-- Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
-- ==========================================================================
--
--                    GENERATED. DO NOT EDIT THIS FILE.
--
-- The schema is db/schema/tables.py, and this is rendered from it by
-- tools/ci/render_schema.py so that it can be read, reviewed or handed to a
-- change-control process without running Python. Edit the Python; re-render.
-- CI fails if the two disagree.
--
-- There are no migrations. Both dialects are applied with CREATE TABLE IF NOT
-- EXISTS, so starting against an existing database is a no-op — which also
-- means an existing table is SKIPPED and a new column never arrives. That is
-- what `run_maya_web.py --check-schema` and `--repair-schema` are for.
--
-- Three column types, one declaration each:
--   TEXT      identifiers, enumerations, and JSON documents held as text
--   INTEGER   counts and sequence numbers
--   BOOLEAN   truth values
--   DOUBLE PRECISION epoch-second timestamps and scores
--
-- Timestamps are epoch seconds rather than a date type: MAYA is bitemporal,
-- event_ts and ingest_ts are compared and arithmetic'd throughout, and the
-- same values live in Delta outside this database entirely.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS ai_capability (
    id TEXT NOT NULL,
    capability_key TEXT NOT NULL,
    description TEXT NOT NULL,
    tier TEXT NOT NULL,
    oracle_key TEXT,
    autonomy TEXT DEFAULT 'human_approved_automation' NOT NULL,
    base_model TEXT NOT NULL,
    prompt_digest TEXT NOT NULL,
    review_sample DOUBLE PRECISION DEFAULT 0.1 NOT NULL,
    token_budget INTEGER,
    cost_budget DOUBLE PRECISION,
    step_budget INTEGER,
    budget_window_days DOUBLE PRECISION DEFAULT 30.0 NOT NULL,
    canary_digest TEXT,
    canary_probes TEXT DEFAULT '[]' NOT NULL,
    canary_taken_at DOUBLE PRECISION,
    status TEXT DEFAULT 'active' NOT NULL,
    owner TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ai_capability_capability_key ON ai_capability (capability_key);

CREATE TABLE IF NOT EXISTS ai_generation (
    id TEXT NOT NULL,
    capability_id TEXT NOT NULL,
    subject_type TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    prompt_digest TEXT NOT NULL,
    base_model TEXT NOT NULL,
    output TEXT DEFAULT '{}' NOT NULL,
    claims TEXT DEFAULT '[]' NOT NULL,
    rejected_claims TEXT DEFAULT '[]' NOT NULL,
    oracle_verdict TEXT DEFAULT '{}' NOT NULL,
    state TEXT DEFAULT 'drafted' NOT NULL,
    sampled BOOLEAN DEFAULT false NOT NULL,
    attested_by TEXT,
    attested_at DOUBLE PRECISION,
    edit_distance DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL,
    created_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_generation_capability ON ai_generation (capability_id, state);

CREATE TABLE IF NOT EXISTS ai_spend (
    id TEXT NOT NULL,
    capability_id TEXT NOT NULL,
    generation_id TEXT,
    tokens INTEGER DEFAULT 0 NOT NULL,
    cost DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    steps INTEGER DEFAULT 1 NOT NULL,
    outcome TEXT DEFAULT 'recorded' NOT NULL,
    spent_at DOUBLE PRECISION NOT NULL,
    spent_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_ai_spend_capability ON ai_spend (capability_id, spent_at);

CREATE TABLE IF NOT EXISTS alias (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    name TEXT NOT NULL,
    version_id TEXT NOT NULL,
    moved_at DOUBLE PRECISION NOT NULL,
    moved_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_alias_model_id_environment_name ON alias (model_id, environment, name);

CREATE TABLE IF NOT EXISTS alias_history (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    name TEXT NOT NULL,
    from_version_id TEXT,
    to_version_id TEXT NOT NULL,
    refinement TEXT DEFAULT '{}' NOT NULL,
    variance TEXT DEFAULT '{}' NOT NULL,
    moved_at DOUBLE PRECISION NOT NULL,
    moved_by TEXT NOT NULL,
    justification TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_alias_history_model ON alias_history (model_id);

CREATE TABLE IF NOT EXISTS amendment (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    reference TEXT NOT NULL,
    reason TEXT NOT NULL,
    scope TEXT DEFAULT '[]' NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    closed_at DOUBLE PRECISION,
    closed_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_amendment_model ON amendment (model_id, status);

CREATE TABLE IF NOT EXISTS api_key (
    id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    username TEXT NOT NULL,
    name TEXT NOT NULL,
    prefix TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    scopes TEXT DEFAULT '[]' NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    created_by TEXT NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    last_used_at DOUBLE PRECISION,
    use_count INTEGER DEFAULT 0 NOT NULL,
    revoked_at DOUBLE PRECISION,
    revoked_by TEXT,
    revoke_reason TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_api_key_key_hash ON api_key (key_hash);
CREATE UNIQUE INDEX IF NOT EXISTS uq_api_key_username_name ON api_key (username, name);

CREATE TABLE IF NOT EXISTS approval_condition (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    reference TEXT NOT NULL,
    kind TEXT NOT NULL,
    enforcement TEXT DEFAULT 'enforced' NOT NULL,
    parameters TEXT DEFAULT '{}' NOT NULL,
    rationale TEXT NOT NULL,
    imposed_by TEXT NOT NULL,
    imposed_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    confirmed_by TEXT,
    confirmed_at DOUBLE PRECISION,
    confirm_every_days DOUBLE PRECISION DEFAULT 30.0 NOT NULL,
    state TEXT DEFAULT 'active' NOT NULL,
    discharged_at DOUBLE PRECISION,
    discharged_by TEXT,
    discharge_reason TEXT DEFAULT '' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_approval_condition_model ON approval_condition (model_id, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_approval_condition_reference ON approval_condition (reference);

CREATE TABLE IF NOT EXISTS artifact_provenance (
    id TEXT NOT NULL,
    artifact_digest TEXT NOT NULL,
    state TEXT NOT NULL,
    predicate TEXT DEFAULT '' NOT NULL,
    builder TEXT,
    why TEXT DEFAULT '' NOT NULL,
    recorded_by TEXT NOT NULL,
    recorded_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_artifact_provenance ON artifact_provenance (artifact_digest);

CREATE TABLE IF NOT EXISTS attachment (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    subject_type TEXT DEFAULT 'model_version' NOT NULL,
    subject_id TEXT,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    filename TEXT NOT NULL,
    media_type TEXT DEFAULT 'application/octet-stream' NOT NULL,
    digest TEXT NOT NULL,
    size_bytes INTEGER DEFAULT 0 NOT NULL,
    text_indexed BOOLEAN DEFAULT false NOT NULL,
    state TEXT DEFAULT 'attached' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    attached_by TEXT NOT NULL,
    attached_at DOUBLE PRECISION NOT NULL,
    reviewed_by TEXT,
    reviewed_at DOUBLE PRECISION,
    review_note TEXT DEFAULT '' NOT NULL,
    supersedes TEXT,
    superseded_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_attachment_model ON attachment (model_id, state);
CREATE INDEX IF NOT EXISTS ix_attachment_version ON attachment (model_version_id, kind);

CREATE TABLE IF NOT EXISTS attestation (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    amendment_id TEXT,
    kind TEXT DEFAULT 'initial' NOT NULL,
    required_roles TEXT DEFAULT '[]' NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    completed_at DOUBLE PRECISION,
    expires_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_attestation_model ON attestation (model_id, status);

CREATE TABLE IF NOT EXISTS attestation_signature (
    id TEXT NOT NULL,
    attestation_id TEXT NOT NULL,
    principal TEXT NOT NULL,
    role TEXT NOT NULL,
    decision TEXT NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    signed_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_signature_attestation ON attestation_signature (attestation_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_signature_attestation_principal ON attestation_signature (attestation_id, principal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_signature_attestation_role ON attestation_signature (attestation_id, role);

CREATE TABLE IF NOT EXISTS authority_band (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    tier INTEGER,
    at_or_above DOUBLE PRECISION DEFAULT 0 NOT NULL,
    legal_entity TEXT,
    stages TEXT DEFAULT '[]' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    published_by TEXT NOT NULL,
    published_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_authority_band ON authority_band (name);

CREATE TABLE IF NOT EXISTS authority_delegation (
    id TEXT NOT NULL,
    principal TEXT NOT NULL,
    ceiling DOUBLE PRECISION NOT NULL,
    currency TEXT DEFAULT 'USD' NOT NULL,
    legal_entity TEXT,
    instrument TEXT NOT NULL,
    granted_by TEXT NOT NULL,
    granted_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_authority_delegation_principal ON authority_delegation (principal, expires_at);

CREATE TABLE IF NOT EXISTS baseline_import (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    source TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    models INTEGER DEFAULT 0 NOT NULL,
    debt_items INTEGER DEFAULT 0 NOT NULL,
    imported_by TEXT NOT NULL,
    imported_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS blob_orphan (
    id TEXT NOT NULL,
    store TEXT NOT NULL,
    digest TEXT NOT NULL,
    bytes INTEGER DEFAULT 0 NOT NULL,
    first_seen_at DOUBLE PRECISION NOT NULL,
    last_seen_at DOUBLE PRECISION NOT NULL,
    sightings INTEGER DEFAULT 1 NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_blob_orphan ON blob_orphan (store, digest);

CREATE TABLE IF NOT EXISTS board_pack (
    id TEXT NOT NULL,
    period TEXT NOT NULL,
    scope TEXT DEFAULT '{}' NOT NULL,
    as_at DOUBLE PRECISION NOT NULL,
    models INTEGER DEFAULT 0 NOT NULL,
    indicators TEXT DEFAULT '[]' NOT NULL,
    exceptions TEXT DEFAULT '[]' NOT NULL,
    unmeasured TEXT DEFAULT '{}' NOT NULL,
    digest TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_board_pack_at ON board_pack (as_at);

CREATE TABLE IF NOT EXISTS breach (
    id TEXT NOT NULL,
    monitor_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    observation_id TEXT NOT NULL,
    severity TEXT NOT NULL,
    consecutive INTEGER DEFAULT 1 NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    finding_id TEXT,
    status TEXT DEFAULT 'open' NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    closed_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_breach_model ON breach (model_id, status);

CREATE TABLE IF NOT EXISTS break_glass (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    principal TEXT NOT NULL,
    requested_by TEXT NOT NULL,
    reason TEXT NOT NULL,
    authorised_by TEXT,
    unilateral BOOLEAN DEFAULT false NOT NULL,
    opened_at DOUBLE PRECISION,
    expires_at DOUBLE PRECISION,
    closed_at DOUBLE PRECISION,
    closed_by TEXT,
    close_reason TEXT DEFAULT '' NOT NULL,
    review_due DOUBLE PRECISION,
    reviewed_at DOUBLE PRECISION,
    reviewed_by TEXT,
    review_outcome TEXT,
    review_note TEXT DEFAULT '' NOT NULL,
    state TEXT DEFAULT 'requested' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_break_glass_principal ON break_glass (principal, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_break_glass_reference ON break_glass (reference);

CREATE TABLE IF NOT EXISTS campaign (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    instruction TEXT DEFAULT '' NOT NULL,
    derivation TEXT DEFAULT '{}' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    due_at DOUBLE PRECISION,
    status TEXT DEFAULT 'open' NOT NULL,
    closed_at DOUBLE PRECISION,
    closed_by TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_campaign_reference ON campaign (reference);

CREATE TABLE IF NOT EXISTS campaign_item (
    id TEXT NOT NULL,
    campaign_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    urn TEXT NOT NULL,
    assignee TEXT NOT NULL,
    assigned_at DOUBLE PRECISION NOT NULL,
    state TEXT DEFAULT 'outstanding' NOT NULL,
    response TEXT DEFAULT '' NOT NULL,
    responded_by TEXT,
    responded_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_campaign_item ON campaign_item (campaign_id, model_id);

CREATE TABLE IF NOT EXISTS compliance_debt (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    import_id TEXT,
    gap_key TEXT NOT NULL,
    description TEXT NOT NULL,
    materiality TEXT DEFAULT 'Medium' NOT NULL,
    tier INTEGER,
    status TEXT DEFAULT 'open' NOT NULL,
    plan TEXT DEFAULT '' NOT NULL,
    owner TEXT NOT NULL,
    finding_id TEXT,
    raised_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    closed_at DOUBLE PRECISION,
    closed_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_debt_model ON compliance_debt (model_id, status);

CREATE TABLE IF NOT EXISTS control_waiver (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    reference TEXT NOT NULL,
    control TEXT NOT NULL,
    rationale TEXT NOT NULL,
    compensating_control TEXT NOT NULL,
    tier_at_grant INTEGER,
    status TEXT DEFAULT 'proposed' NOT NULL,
    proposed_by TEXT NOT NULL,
    approved_by TEXT,
    approvals TEXT DEFAULT '[]' NOT NULL,
    granted_at DOUBLE PRECISION,
    expires_at DOUBLE PRECISION NOT NULL,
    renewals INTEGER DEFAULT 0 NOT NULL,
    finding_id TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    closed_at DOUBLE PRECISION,
    closure_reason TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_control_waiver_model_id_reference ON control_waiver (model_id, reference);

CREATE TABLE IF NOT EXISTS dataset_snapshot (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT DEFAULT 'training' NOT NULL,
    delta_table TEXT NOT NULL,
    delta_version BIGINT DEFAULT 0 NOT NULL,
    row_count INTEGER DEFAULT 0 NOT NULL,
    as_of DOUBLE PRECISION NOT NULL,
    pit_verified BOOLEAN DEFAULT false NOT NULL,
    pit_report TEXT DEFAULT '{}' NOT NULL,
    featureset TEXT,
    featureset_version INTEGER,
    digest TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS derived_feature (
    id TEXT NOT NULL,
    feature_id TEXT NOT NULL,
    name TEXT NOT NULL,
    expression TEXT NOT NULL,
    inputs TEXT DEFAULT '[]' NOT NULL,
    evaluator TEXT DEFAULT 'internal' NOT NULL,
    on_error TEXT DEFAULT 'null' NOT NULL,
    definition_version INTEGER DEFAULT 1 NOT NULL,
    digest TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_derived_feature ON derived_feature (feature_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_derived_feature_name_definition_version ON derived_feature (name, definition_version);

CREATE TABLE IF NOT EXISTS discovery_candidate (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    source TEXT NOT NULL,
    scanner TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    location TEXT NOT NULL,
    evidence TEXT DEFAULT '{}' NOT NULL,
    proposed_as TEXT DEFAULT 'model' NOT NULL,
    confidence DOUBLE PRECISION,
    state TEXT DEFAULT 'open' NOT NULL,
    outcome TEXT,
    outcome_note TEXT DEFAULT '' NOT NULL,
    registered_urn TEXT,
    triaged_by TEXT,
    triaged_at DOUBLE PRECISION,
    found_at DOUBLE PRECISION NOT NULL,
    last_seen_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_discovery_state ON discovery_candidate (state, scanner);
CREATE UNIQUE INDEX IF NOT EXISTS uq_discovery_fingerprint ON discovery_candidate (scanner, fingerprint);

CREATE TABLE IF NOT EXISTS document (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    subject_type TEXT DEFAULT 'model_version' NOT NULL,
    subject_id TEXT,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    sections TEXT DEFAULT '[]' NOT NULL,
    citations TEXT DEFAULT '[]' NOT NULL,
    coverage TEXT DEFAULT '{}' NOT NULL,
    digest TEXT NOT NULL,
    subjects TEXT DEFAULT '[]' NOT NULL,
    evidence_head INTEGER DEFAULT 0 NOT NULL,
    status TEXT DEFAULT 'compiled' NOT NULL,
    compiled_at DOUBLE PRECISION NOT NULL,
    compiled_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_document_model ON document (model_id, kind);

CREATE TABLE IF NOT EXISTS document_comment (
    id TEXT NOT NULL,
    document_id TEXT NOT NULL,
    document_digest TEXT NOT NULL,
    section TEXT NOT NULL,
    quote TEXT DEFAULT '' NOT NULL,
    body TEXT NOT NULL,
    asks_for TEXT DEFAULT 'comment' NOT NULL,
    raised_by TEXT NOT NULL,
    raised_at DOUBLE PRECISION NOT NULL,
    state TEXT DEFAULT 'open' NOT NULL,
    resolution TEXT DEFAULT '' NOT NULL,
    resolved_by TEXT,
    resolved_at DOUBLE PRECISION,
    evidence_id TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_document_comment ON document_comment (document_id, state);

CREATE TABLE IF NOT EXISTS elicitation (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    question TEXT NOT NULL,
    units TEXT DEFAULT '' NOT NULL,
    panel TEXT DEFAULT '[]' NOT NULL,
    facilitator TEXT NOT NULL,
    method TEXT DEFAULT 'delphi' NOT NULL,
    round INTEGER DEFAULT 1 NOT NULL,
    state TEXT DEFAULT 'open' NOT NULL,
    final_value DOUBLE PRECISION,
    final_note TEXT DEFAULT '' NOT NULL,
    concluded_by TEXT,
    opened_at DOUBLE PRECISION NOT NULL,
    concluded_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_elicitation_reference ON elicitation (reference);

CREATE TABLE IF NOT EXISTS elicitation_response (
    id TEXT NOT NULL,
    elicitation_id TEXT NOT NULL,
    round INTEGER NOT NULL,
    panellist TEXT NOT NULL,
    value DOUBLE PRECISION,
    confidence TEXT DEFAULT '' NOT NULL,
    reasoning TEXT DEFAULT '' NOT NULL,
    independent BOOLEAN DEFAULT true NOT NULL,
    dissented BOOLEAN DEFAULT false NOT NULL,
    recorded_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_elicitation_response ON elicitation_response (elicitation_id, round, panellist);

CREATE TABLE IF NOT EXISTS estate_cost (
    id TEXT NOT NULL,
    model_id TEXT,
    urn TEXT DEFAULT '' NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    currency TEXT NOT NULL,
    period_start DOUBLE PRECISION NOT NULL,
    period_end DOUBLE PRECISION NOT NULL,
    source TEXT NOT NULL,
    reference TEXT DEFAULT '' NOT NULL,
    owner TEXT DEFAULT '' NOT NULL,
    legal_entity TEXT DEFAULT '' NOT NULL,
    domain TEXT DEFAULT '' NOT NULL,
    state TEXT DEFAULT 'attributed' NOT NULL,
    recorded_by TEXT NOT NULL,
    recorded_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_estate_cost_model ON estate_cost (model_id, period_start);
CREATE INDEX IF NOT EXISTS ix_estate_cost_period ON estate_cost (period_start, period_end);

CREATE TABLE IF NOT EXISTS event_subscription (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    name TEXT NOT NULL,
    url TEXT NOT NULL,
    kinds TEXT DEFAULT '[]' NOT NULL,
    secret TEXT NOT NULL,
    cursor INTEGER DEFAULT 0 NOT NULL,
    state TEXT DEFAULT 'active' NOT NULL,
    failures INTEGER DEFAULT 0 NOT NULL,
    last_delivery_at DOUBLE PRECISION,
    last_failure_at DOUBLE PRECISION,
    last_failure TEXT DEFAULT '' NOT NULL,
    owner TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    created_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_event_subscription_reference ON event_subscription (reference);

CREATE TABLE IF NOT EXISTS evidence_checkpoint (
    id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    chain_hash TEXT NOT NULL,
    verified_at DOUBLE PRECISION NOT NULL,
    verified_by TEXT DEFAULT 'system' NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS evidence_node (
    id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    kind TEXT NOT NULL,
    subject_type TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    payload TEXT DEFAULT '{}' NOT NULL,
    parents TEXT DEFAULT '[]' NOT NULL,
    contains_personal_data BOOLEAN DEFAULT false NOT NULL,
    content_hash TEXT NOT NULL,
    prev_hash TEXT NOT NULL,
    chain_hash TEXT NOT NULL,
    trust DOUBLE PRECISION DEFAULT 1.0 NOT NULL,
    recorded_at DOUBLE PRECISION NOT NULL,
    recorded_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_evidence_subject ON evidence_node (subject_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_evidence_node_seq ON evidence_node (seq);

CREATE TABLE IF NOT EXISTS export_share (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    model_id TEXT,
    urn TEXT NOT NULL,
    content_digest TEXT NOT NULL,
    pack_digest TEXT NOT NULL,
    filename TEXT DEFAULT '' NOT NULL,
    recipient TEXT NOT NULL,
    purpose TEXT DEFAULT '' NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    max_reads INTEGER,
    reads INTEGER DEFAULT 0 NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    revoked_at DOUBLE PRECISION,
    revoked_by TEXT,
    revoke_reason TEXT DEFAULT '' NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_export_share_reference ON export_share (reference);

CREATE TABLE IF NOT EXISTS export_share_read (
    id TEXT NOT NULL,
    share_id TEXT NOT NULL,
    at DOUBLE PRECISION NOT NULL,
    outcome TEXT NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_export_share_read ON export_share_read (share_id, at);

CREATE TABLE IF NOT EXISTS feature (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    entity TEXT NOT NULL,
    dtype TEXT NOT NULL,
    description TEXT NOT NULL,
    business_definition TEXT,
    owner TEXT NOT NULL,
    source_system TEXT,
    sensitivity TEXT DEFAULT 'internal' NOT NULL,
    pii BOOLEAN DEFAULT false NOT NULL,
    protected_basis BOOLEAN DEFAULT false NOT NULL,
    proxy_risk TEXT DEFAULT 'none' NOT NULL,
    assertions TEXT DEFAULT '[]' NOT NULL,
    defaults TEXT DEFAULT '{}' NOT NULL,
    shape TEXT DEFAULT '[]' NOT NULL,
    components TEXT DEFAULT '[]' NOT NULL,
    composes TEXT DEFAULT '[]' NOT NULL,
    operations TEXT DEFAULT '[]' NOT NULL,
    definition_version INTEGER DEFAULT 1 NOT NULL,
    sealed_at DOUBLE PRECISION,
    sealed_by TEXT,
    seal_note TEXT DEFAULT '' NOT NULL,
    ephemeral BOOLEAN DEFAULT false NOT NULL,
    expires_at DOUBLE PRECISION,
    created_by TEXT DEFAULT 'system' NOT NULL,
    certification TEXT DEFAULT 'experimental' NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    retired_at DOUBLE PRECISION,
    retired_by TEXT,
    retire_reason TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_feature_entity ON feature (entity);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_name ON feature (name);

CREATE TABLE IF NOT EXISTS feature_contract (
    id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    digest TEXT NOT NULL,
    items TEXT DEFAULT '[]' NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_contract_model_version_id ON feature_contract (model_version_id);

CREATE TABLE IF NOT EXISTS feature_source (
    id TEXT NOT NULL,
    view_name TEXT NOT NULL,
    kind TEXT NOT NULL,
    locator TEXT NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    format TEXT DEFAULT '' NOT NULL,
    options TEXT DEFAULT '{}' NOT NULL,
    credential_ref TEXT,
    enabled BOOLEAN DEFAULT true NOT NULL,
    last_pulled_at DOUBLE PRECISION,
    last_pull_rows INTEGER,
    last_pull_digest TEXT,
    last_pull_detail TEXT DEFAULT '' NOT NULL,
    last_pull_version INTEGER,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    retired_at DOUBLE PRECISION,
    retired_by TEXT,
    retire_reason TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_feature_source_kind ON feature_source (kind);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_source_view ON feature_source (view_name);

CREATE TABLE IF NOT EXISTS feature_view (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    entity TEXT NOT NULL,
    owner TEXT NOT NULL,
    description TEXT,
    delta_table TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_view_name ON feature_view (name);

CREATE TABLE IF NOT EXISTS feature_view_version (
    id TEXT NOT NULL,
    feature_view_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    features TEXT DEFAULT '[]' NOT NULL,
    delta_version BIGINT DEFAULT 0 NOT NULL,
    valid_time_column TEXT DEFAULT 'event_ts' NOT NULL,
    ingest_time_column TEXT DEFAULT 'ingest_ts' NOT NULL,
    row_count INTEGER DEFAULT 0 NOT NULL,
    quarantined BOOLEAN DEFAULT false NOT NULL,
    assertion_report TEXT DEFAULT '{}' NOT NULL,
    quality_report TEXT DEFAULT '{}' NOT NULL,
    materialised_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_fvv_view ON feature_view_version (feature_view_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_view_version_feature_view_id_version ON feature_view_version (feature_view_id, version);

CREATE TABLE IF NOT EXISTS featureset (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    entity TEXT NOT NULL,
    owner TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    slots TEXT DEFAULT '{}' NOT NULL,
    label_slot TEXT,
    outcome_window_days INTEGER DEFAULT 0 NOT NULL,
    defaults TEXT DEFAULT '{}' NOT NULL,
    composes TEXT DEFAULT '[]' NOT NULL,
    operations TEXT DEFAULT '[]' NOT NULL,
    definition_version INTEGER DEFAULT 1 NOT NULL,
    sealed_at DOUBLE PRECISION,
    sealed_by TEXT,
    seal_note TEXT DEFAULT '' NOT NULL,
    ephemeral BOOLEAN DEFAULT false NOT NULL,
    expires_at DOUBLE PRECISION,
    grain TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    retired_at DOUBLE PRECISION,
    retired_by TEXT,
    retire_reason TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_featureset_name ON featureset (name);

CREATE TABLE IF NOT EXISTS featureset_version (
    id TEXT NOT NULL,
    featureset_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    bindings TEXT DEFAULT '{}' NOT NULL,
    label_binding TEXT DEFAULT '{}' NOT NULL,
    digest TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_fsv_set ON featureset_version (featureset_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_featureset_version_featureset_id_version ON featureset_version (featureset_id, version);

CREATE TABLE IF NOT EXISTS finding (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    validation_id TEXT,
    source TEXT DEFAULT 'validation' NOT NULL,
    severity TEXT NOT NULL,
    category TEXT DEFAULT 'general' NOT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    affected_component TEXT,
    blocking BOOLEAN DEFAULT false NOT NULL,
    owner TEXT NOT NULL,
    raised_at DOUBLE PRECISION NOT NULL,
    due_at DOUBLE PRECISION NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    closed_at DOUBLE PRECISION,
    closure_verified_by TEXT,
    closure_evidence TEXT DEFAULT '{}' NOT NULL,
    root_id TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_finding_open ON finding (model_id, status, severity);
CREATE INDEX IF NOT EXISTS ix_finding_root ON finding (root_id);

CREATE TABLE IF NOT EXISTS finding_action (
    id TEXT NOT NULL,
    finding_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    act TEXT NOT NULL,
    actor TEXT NOT NULL,
    from_owner TEXT,
    to_owner TEXT,
    reason TEXT DEFAULT '' NOT NULL,
    plan TEXT DEFAULT '' NOT NULL,
    committed_at DOUBLE PRECISION,
    due_before DOUBLE PRECISION,
    due_after DOUBLE PRECISION,
    acted_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_finding_action ON finding_action (finding_id, acted_at);

CREATE TABLE IF NOT EXISTS finding_root (
    id TEXT NOT NULL,
    title TEXT NOT NULL,
    kind TEXT NOT NULL,
    detail TEXT NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    addressed_at DOUBLE PRECISION,
    addressed_by TEXT DEFAULT '' NOT NULL,
    addressed_note TEXT DEFAULT '' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_finding_root_open ON finding_root (status, kind);

CREATE TABLE IF NOT EXISTS idempotency (
    id TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    principal TEXT NOT NULL,
    method TEXT NOT NULL,
    path TEXT NOT NULL,
    request_digest TEXT NOT NULL,
    state TEXT DEFAULT 'in_flight' NOT NULL,
    status INTEGER,
    body TEXT,
    started_at DOUBLE PRECISION NOT NULL,
    completed_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_idempotency_started ON idempotency (started_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_idempotency ON idempotency (idempotency_key, principal);

CREATE TABLE IF NOT EXISTS inference (
    id TEXT NOT NULL,
    invocation_id TEXT,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    request_id TEXT,
    principal TEXT NOT NULL,
    feature_digest TEXT NOT NULL,
    prediction_digest TEXT NOT NULL,
    features TEXT,
    prediction TEXT,
    explanation TEXT,
    latency_ms DOUBLE PRECISION,
    outcome TEXT DEFAULT 'ok' NOT NULL,
    reason TEXT DEFAULT 'sampled' NOT NULL,
    classification TEXT DEFAULT 'internal' NOT NULL,
    retain_until DOUBLE PRECISION,
    at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_inference_model ON inference (model_id, at);
CREATE INDEX IF NOT EXISTS ix_inference_retention ON inference (retain_until);

CREATE TABLE IF NOT EXISTS intake_proposal (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    proposed_by TEXT NOT NULL,
    business_area TEXT DEFAULT '' NOT NULL,
    proposed_at DOUBLE PRECISION NOT NULL,
    in_scope BOOLEAN,
    sourcing TEXT,
    generative BOOLEAN,
    rationale TEXT DEFAULT '{}' NOT NULL,
    state TEXT DEFAULT 'proposed' NOT NULL,
    triaged_by TEXT,
    triaged_at DOUBLE PRECISION,
    registered_urn TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_intake_reference ON intake_proposal (reference);

CREATE TABLE IF NOT EXISTS legal_hold (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    matter TEXT NOT NULL,
    scope_kind TEXT NOT NULL,
    scope_id TEXT,
    classes TEXT DEFAULT '[]' NOT NULL,
    owner TEXT NOT NULL,
    placed_by TEXT NOT NULL,
    placed_at DOUBLE PRECISION NOT NULL,
    state TEXT DEFAULT 'active' NOT NULL,
    lifted_at DOUBLE PRECISION,
    lifted_by TEXT,
    lift_reason TEXT DEFAULT '' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_legal_hold_state ON legal_hold (state, scope_kind);
CREATE UNIQUE INDEX IF NOT EXISTS uq_legal_hold_reference ON legal_hold (reference);

CREATE TABLE IF NOT EXISTS model (
    id TEXT NOT NULL,
    urn TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    model_class TEXT NOT NULL,
    domain TEXT NOT NULL,
    owner TEXT NOT NULL,
    legal_entity TEXT NOT NULL,
    purpose TEXT NOT NULL,
    origin TEXT DEFAULT 'internal' NOT NULL,
    status TEXT DEFAULT 'draft' NOT NULL,
    tier INTEGER,
    designations TEXT DEFAULT '[]' NOT NULL,
    attributes TEXT DEFAULT '{}' NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    created_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_model_domain ON model (domain);
CREATE INDEX IF NOT EXISTS ix_model_tier ON model (tier);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_urn ON model (urn);

CREATE TABLE IF NOT EXISTS model_assumption (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    reference TEXT NOT NULL,
    kind TEXT NOT NULL,
    statement TEXT NOT NULL,
    monitor_id TEXT,
    basis TEXT DEFAULT '' NOT NULL,
    owner TEXT DEFAULT '' NOT NULL,
    materiality TEXT DEFAULT 'moderate' NOT NULL,
    mitigation TEXT DEFAULT '' NOT NULL,
    review_due DOUBLE PRECISION,
    finding_id TEXT,
    overlay_id TEXT,
    raised_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    withdrawn_at DOUBLE PRECISION,
    withdrawn_by TEXT,
    withdrawal_reason TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_assumption_model_version_id_reference ON model_assumption (model_version_id, reference);

CREATE TABLE IF NOT EXISTS model_decommission (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    urn TEXT NOT NULL,
    rationale TEXT NOT NULL,
    replacement TEXT NOT NULL,
    retention_class TEXT NOT NULL,
    notified TEXT DEFAULT '[]' NOT NULL,
    unnotified TEXT DEFAULT '[]' NOT NULL,
    acknowledged BOOLEAN DEFAULT false NOT NULL,
    consumers_known BOOLEAN DEFAULT false NOT NULL,
    decommissioned_by TEXT NOT NULL,
    decommissioned_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_decommission ON model_decommission (model_id);

CREATE TABLE IF NOT EXISTS model_edge (
    id TEXT NOT NULL,
    from_model TEXT NOT NULL,
    to_model TEXT NOT NULL,
    kind TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    type_checked BOOLEAN DEFAULT false NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_edge_from ON model_edge (from_model);
CREATE INDEX IF NOT EXISTS ix_edge_to ON model_edge (to_model);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_edge_from_model_to_model_kind ON model_edge (from_model, to_model, kind);

CREATE TABLE IF NOT EXISTS model_limitation (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    reference TEXT NOT NULL,
    kind TEXT NOT NULL,
    statement TEXT NOT NULL,
    bound_key TEXT,
    basis TEXT DEFAULT '' NOT NULL,
    owner TEXT DEFAULT '' NOT NULL,
    materiality TEXT DEFAULT 'moderate' NOT NULL,
    mitigation TEXT DEFAULT '' NOT NULL,
    review_due DOUBLE PRECISION,
    finding_id TEXT,
    overlay_id TEXT,
    raised_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    withdrawn_at DOUBLE PRECISION,
    withdrawn_by TEXT,
    withdrawal_reason TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_limitation_model_version_id_reference ON model_limitation (model_version_id, reference);

CREATE TABLE IF NOT EXISTS model_tombstone (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    urn TEXT NOT NULL,
    name TEXT NOT NULL,
    model_class TEXT DEFAULT '' NOT NULL,
    domain TEXT DEFAULT '' NOT NULL,
    owner TEXT DEFAULT '' NOT NULL,
    legal_entity TEXT DEFAULT '' NOT NULL,
    status TEXT NOT NULL,
    tier INTEGER,
    registered_at DOUBLE PRECISION,
    deleted_at DOUBLE PRECISION NOT NULL,
    deleted_by TEXT NOT NULL,
    reason TEXT NOT NULL,
    destroyed TEXT DEFAULT '{}' NOT NULL,
    compacted_at DOUBLE PRECISION,
    compacted_by TEXT,
    reclaimed TEXT DEFAULT '{}' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_model_tombstone_deleted ON model_tombstone (deleted_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_tombstone_urn ON model_tombstone (urn);

CREATE TABLE IF NOT EXISTS model_use (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    reference TEXT NOT NULL,
    declared_use TEXT NOT NULL,
    name TEXT NOT NULL,
    purpose TEXT DEFAULT '' NOT NULL,
    product TEXT DEFAULT '' NOT NULL,
    legal_entity TEXT DEFAULT '' NOT NULL,
    geography TEXT DEFAULT '' NOT NULL,
    channel TEXT DEFAULT '' NOT NULL,
    segment TEXT DEFAULT '' NOT NULL,
    decision_authority TEXT DEFAULT '' NOT NULL,
    owner TEXT NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    effective_from DOUBLE PRECISION NOT NULL,
    effective_to DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL,
    created_by TEXT NOT NULL,
    retired_at DOUBLE PRECISION,
    retired_by TEXT,
    retire_reason TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_model_use_declared_use ON model_use (declared_use);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_use_model_id_reference ON model_use (model_id, reference);

CREATE TABLE IF NOT EXISTS model_version (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    semver TEXT NOT NULL,
    manifest TEXT NOT NULL,
    manifest_digest TEXT NOT NULL,
    trainability_class TEXT NOT NULL,
    parameter_kind TEXT NOT NULL,
    fit_procedure TEXT NOT NULL,
    deterministic BOOLEAN DEFAULT true NOT NULL,
    input_schema TEXT DEFAULT '[]' NOT NULL,
    parameter_schema TEXT DEFAULT '[]' NOT NULL,
    output_schema TEXT DEFAULT '[]' NOT NULL,
    contract TEXT DEFAULT '{}' NOT NULL,
    artifact_digest TEXT,
    artifact_uri TEXT,
    artifact_size INTEGER,
    status TEXT DEFAULT 'draft' NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    created_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_version_model ON model_version (model_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_version_model_id_semver ON model_version (model_id, semver);

CREATE TABLE IF NOT EXISTS monitor (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,
    test_key TEXT NOT NULL,
    threshold TEXT DEFAULT '{}' NOT NULL,
    slice TEXT DEFAULT '{}' NOT NULL,
    reference TEXT DEFAULT '{}' NOT NULL,
    cadence_days DOUBLE PRECISION DEFAULT 1.0 NOT NULL,
    label_delay_days DOUBLE PRECISION DEFAULT 0.0 NOT NULL,
    breach_severity TEXT DEFAULT 'Medium' NOT NULL,
    escalate_after INTEGER DEFAULT 3 NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    owner TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    last_evaluated_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_monitor_model ON monitor (model_id, status);

CREATE TABLE IF NOT EXISTS monitoring_plan (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    items TEXT DEFAULT '[]' NOT NULL,
    rationale TEXT DEFAULT '' NOT NULL,
    authored_by TEXT NOT NULL,
    authored_at DOUBLE PRECISION NOT NULL,
    inherited_at DOUBLE PRECISION,
    inherited_by TEXT,
    monitor_ids TEXT DEFAULT '[]' NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_monitoring_plan_model_version_id ON monitoring_plan (model_version_id);

CREATE TABLE IF NOT EXISTS notification (
    id TEXT NOT NULL,
    principal TEXT NOT NULL,
    channel TEXT NOT NULL,
    state TEXT NOT NULL,
    digest TEXT NOT NULL,
    item_count INTEGER DEFAULT 0 NOT NULL,
    overdue INTEGER DEFAULT 0 NOT NULL,
    summary TEXT DEFAULT '' NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    sent_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_notification_principal ON notification (principal);

CREATE TABLE IF NOT EXISTS observation (
    id TEXT NOT NULL,
    monitor_id TEXT NOT NULL,
    value DOUBLE PRECISION,
    passed BOOLEAN DEFAULT false NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    sample_size INTEGER DEFAULT 0 NOT NULL,
    window_start DOUBLE PRECISION,
    window_end DOUBLE PRECISION,
    matured BOOLEAN DEFAULT true NOT NULL,
    source TEXT DEFAULT 'maya' NOT NULL,
    computed_by TEXT DEFAULT '' NOT NULL,
    method TEXT DEFAULT '' NOT NULL,
    digest TEXT NOT NULL,
    computed_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_observation_monitor ON observation (monitor_id, computed_at);

CREATE TABLE IF NOT EXISTS overlay (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    reference TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,
    direction TEXT DEFAULT 'increase' NOT NULL,
    rationale TEXT NOT NULL,
    basis TEXT DEFAULT '{}' NOT NULL,
    owner TEXT NOT NULL,
    proposed_by TEXT NOT NULL,
    approved_by TEXT,
    status TEXT DEFAULT 'proposed' NOT NULL,
    effective_from DOUBLE PRECISION,
    expires_at DOUBLE PRECISION,
    renewals INTEGER DEFAULT 0 NOT NULL,
    finding_id TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    closed_at DOUBLE PRECISION,
    closure_reason TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_overlay_model ON overlay (model_id, status);

CREATE TABLE IF NOT EXISTS overlay_measurement (
    id TEXT NOT NULL,
    overlay_id TEXT NOT NULL,
    period TEXT NOT NULL,
    base_value DOUBLE PRECISION NOT NULL,
    adjusted_value DOUBLE PRECISION NOT NULL,
    magnitude DOUBLE PRECISION NOT NULL,
    pct_of_base DOUBLE PRECISION,
    measured_by TEXT NOT NULL,
    measured_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_measurement_overlay ON overlay_measurement (overlay_id, period);

CREATE TABLE IF NOT EXISTS parallel_observation (
    id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    input_key TEXT NOT NULL,
    champion DOUBLE PRECISION,
    challenger DOUBLE PRECISION,
    outcome DOUBLE PRECISION,
    outcome_at DOUBLE PRECISION,
    at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_parallel_observation_run ON parallel_observation (run_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_parallel_observation ON parallel_observation (run_id, input_key);

CREATE TABLE IF NOT EXISTS parallel_run (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    model_id TEXT NOT NULL,
    champion_version_id TEXT NOT NULL,
    challenger_version_id TEXT NOT NULL,
    champion_semver TEXT NOT NULL,
    challenger_semver TEXT NOT NULL,
    purpose TEXT NOT NULL,
    tolerance DOUBLE PRECISION DEFAULT 1e-9 NOT NULL,
    state TEXT DEFAULT 'running' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    closed_at DOUBLE PRECISION,
    closed_by TEXT,
    conclusion TEXT,
    close_note TEXT DEFAULT '' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_parallel_run_model ON parallel_run (model_id, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_parallel_run_reference ON parallel_run (reference);

CREATE TABLE IF NOT EXISTS parameter_set (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    name TEXT NOT NULL,
    version INTEGER DEFAULT 1 NOT NULL,
    kind TEXT NOT NULL,
    provenance TEXT NOT NULL,
    values_inline TEXT DEFAULT '{}' NOT NULL,
    values_uri TEXT,
    cardinality INTEGER DEFAULT 0 NOT NULL,
    diagnostics TEXT DEFAULT '{}' NOT NULL,
    featureset_version_id TEXT,
    window_from DOUBLE PRECISION,
    window_to DOUBLE PRECISION,
    as_of DOUBLE PRECISION,
    snapshot_id TEXT,
    warrant_id TEXT,
    digest TEXT NOT NULL,
    state TEXT DEFAULT 'proposed' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    approved_by TEXT,
    approved_at DOUBLE PRECISION,
    review_note TEXT DEFAULT '' NOT NULL,
    superseded_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_parameter_set_version ON parameter_set (model_version_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_parameter_set_model_version_id_name_version ON parameter_set (model_version_id, name, version);

CREATE TABLE IF NOT EXISTS policy_rule (
    id TEXT NOT NULL,
    gate TEXT NOT NULL,
    version INTEGER NOT NULL,
    rule TEXT NOT NULL,
    reason TEXT NOT NULL,
    cases TEXT DEFAULT '[]' NOT NULL,
    facts_read TEXT DEFAULT '[]' NOT NULL,
    test_report TEXT DEFAULT '{}' NOT NULL,
    state TEXT DEFAULT 'draft' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    digest TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    published_at DOUBLE PRECISION,
    published_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_policy_gate ON policy_rule (gate, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_policy_rule_gate_version ON policy_rule (gate, version);

CREATE TABLE IF NOT EXISTS principal (
    id TEXT NOT NULL,
    username TEXT NOT NULL,
    display_name TEXT NOT NULL,
    kind TEXT DEFAULT 'person' NOT NULL,
    email TEXT,
    roles TEXT DEFAULT '[]' NOT NULL,
    legal_entities TEXT DEFAULT '[]' NOT NULL,
    domains TEXT DEFAULT '[]' NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    password_hash TEXT,
    password_salt TEXT,
    sso_issuer TEXT,
    sso_subject TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    last_seen_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_principal_status ON principal (status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_principal_username ON principal (username);

CREATE TABLE IF NOT EXISTS recertification (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    title TEXT DEFAULT '' NOT NULL,
    reviewer TEXT NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    closed_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_recertification ON recertification (reference);

CREATE TABLE IF NOT EXISTS recertification_item (
    id TEXT NOT NULL,
    campaign_reference TEXT NOT NULL,
    principal TEXT NOT NULL,
    roles TEXT DEFAULT '[]' NOT NULL,
    legal_entities TEXT DEFAULT '[]' NOT NULL,
    domains TEXT DEFAULT '[]' NOT NULL,
    last_seen_at DOUBLE PRECISION,
    state TEXT DEFAULT 'unreviewed' NOT NULL,
    reason TEXT DEFAULT '' NOT NULL,
    answered_by TEXT DEFAULT '' NOT NULL,
    answered_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_recertification_item_principal ON recertification_item (principal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_recertification_item ON recertification_item (campaign_reference, principal);

CREATE TABLE IF NOT EXISTS regulatory_approval (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    model_id TEXT,
    kind TEXT NOT NULL,
    regulator TEXT NOT NULL,
    scope TEXT NOT NULL,
    conditions TEXT DEFAULT '' NOT NULL,
    granted_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION,
    state TEXT DEFAULT 'in_force' NOT NULL,
    withdrawn_at DOUBLE PRECISION,
    withdrawn_by TEXT,
    withdrawal_reason TEXT DEFAULT '' NOT NULL,
    recorded_by TEXT NOT NULL,
    recorded_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_regulatory_approval_model ON regulatory_approval (model_id, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_regulatory_approval_reference ON regulatory_approval (reference);

CREATE TABLE IF NOT EXISTS retrain_policy (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    triggers TEXT DEFAULT '[]' NOT NULL,
    tolerance TEXT DEFAULT '{}' NOT NULL,
    auto_accept BOOLEAN DEFAULT false NOT NULL,
    rationale TEXT DEFAULT '' NOT NULL,
    declared_by TEXT NOT NULL,
    approved_by TEXT,
    declared_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION,
    status TEXT DEFAULT 'active' NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_retrain_policy_model ON retrain_policy (model_id);

CREATE TABLE IF NOT EXISTS risk_appetite (
    id TEXT NOT NULL,
    metric TEXT NOT NULL,
    scope_key TEXT DEFAULT '*' NOT NULL,
    scope TEXT DEFAULT '{}' NOT NULL,
    version INTEGER NOT NULL,
    limit_value DOUBLE PRECISION NOT NULL,
    amber_value DOUBLE PRECISION,
    direction TEXT NOT NULL,
    unit TEXT NOT NULL,
    rationale TEXT NOT NULL,
    owner TEXT DEFAULT '' NOT NULL,
    review_at DOUBLE PRECISION,
    retired BOOLEAN DEFAULT false NOT NULL,
    digest TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    retired_at DOUBLE PRECISION,
    retired_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_appetite_metric ON risk_appetite (metric, retired);
CREATE UNIQUE INDEX IF NOT EXISTS uq_risk_appetite_metric_scope_key_version ON risk_appetite (metric, scope_key, version);

CREATE TABLE IF NOT EXISTS risk_assessment (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    tier INTEGER NOT NULL,
    materiality TEXT NOT NULL,
    complexity TEXT NOT NULL,
    facts TEXT DEFAULT '{}' NOT NULL,
    required_controls TEXT DEFAULT '[]' NOT NULL,
    rationale TEXT NOT NULL,
    ruleset_version TEXT NOT NULL,
    next_review_due DOUBLE PRECISION,
    assessed_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_risk_model ON risk_assessment (model_id);

CREATE TABLE IF NOT EXISTS role (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    permissions TEXT DEFAULT '[]' NOT NULL,
    built_in BOOLEAN DEFAULT false NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    created_by TEXT DEFAULT 'system' NOT NULL,
    updated_at DOUBLE PRECISION,
    updated_by TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_role_name ON role (name);

CREATE TABLE IF NOT EXISTS run (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    model_id TEXT,
    model_version_id TEXT,
    verb TEXT NOT NULL,
    warrant_id TEXT,
    parent_id TEXT,
    purpose TEXT DEFAULT '' NOT NULL,
    resource_profile TEXT DEFAULT '{}' NOT NULL,
    environment TEXT DEFAULT '{}' NOT NULL,
    inputs TEXT DEFAULT '{}' NOT NULL,
    hyperparameters TEXT DEFAULT '{}' NOT NULL,
    seeds TEXT DEFAULT '{}' NOT NULL,
    log_uri TEXT DEFAULT '' NOT NULL,
    metrics TEXT DEFAULT '{}' NOT NULL,
    parameter_set_id TEXT,
    state TEXT DEFAULT 'open' NOT NULL,
    outcome_note TEXT DEFAULT '' NOT NULL,
    expected_seconds DOUBLE PRECISION,
    cost DOUBLE PRECISION,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    closed_at DOUBLE PRECISION,
    closed_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_run_parent ON run (parent_id, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_run_reference ON run (reference);

CREATE TABLE IF NOT EXISTS saved_view (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    entity TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    query TEXT DEFAULT '{}' NOT NULL,
    owner TEXT NOT NULL,
    shared BOOLEAN DEFAULT false NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    last_run_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_saved_view_name ON saved_view (owner, name);

CREATE TABLE IF NOT EXISTS scheduled_run (
    id TEXT NOT NULL,
    job TEXT NOT NULL,
    outcome TEXT DEFAULT '{}' NOT NULL,
    ok BOOLEAN DEFAULT true NOT NULL,
    error TEXT,
    duration_ms DOUBLE PRECISION DEFAULT 0 NOT NULL,
    ran_by TEXT NOT NULL,
    ran_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_scheduled_run_job ON scheduled_run (job, ran_at);

CREATE TABLE IF NOT EXISTS serving_attestation (
    id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    warrant_id TEXT,
    descriptor_id TEXT,
    served TEXT DEFAULT '{}' NOT NULL,
    pinned TEXT DEFAULT '{}' NOT NULL,
    agrees BOOLEAN DEFAULT false NOT NULL,
    divergence TEXT DEFAULT '[]' NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    attested_by TEXT NOT NULL,
    attested_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_serving_version ON serving_attestation (model_version_id);

CREATE TABLE IF NOT EXISTS supervisory_matter (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    kind TEXT NOT NULL,
    supervisor TEXT NOT NULL,
    examination TEXT DEFAULT '' NOT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    severity TEXT DEFAULT 'High' NOT NULL,
    scope TEXT DEFAULT '[]' NOT NULL,
    owner TEXT NOT NULL,
    raised_at DOUBLE PRECISION NOT NULL,
    committed_at DOUBLE PRECISION,
    status TEXT DEFAULT 'open' NOT NULL,
    closed_at DOUBLE PRECISION,
    closure_note TEXT DEFAULT '' NOT NULL,
    closed_by TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_supervisory_reference ON supervisory_matter (reference);

CREATE TABLE IF NOT EXISTS telemetry_batch (
    id TEXT NOT NULL,
    digest TEXT NOT NULL,
    delta_table TEXT NOT NULL,
    row_count INTEGER DEFAULT 0 NOT NULL,
    at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_telemetry_batch_digest ON telemetry_batch (digest);

CREATE TABLE IF NOT EXISTS test_result (
    id TEXT NOT NULL,
    validation_id TEXT NOT NULL,
    test_key TEXT NOT NULL,
    parameters TEXT DEFAULT '{}' NOT NULL,
    slice TEXT DEFAULT '{}' NOT NULL,
    value DOUBLE PRECISION,
    threshold TEXT DEFAULT '{}' NOT NULL,
    passed BOOLEAN DEFAULT false NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    digest TEXT NOT NULL,
    computed_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_test_result_validation ON test_result (validation_id, test_key);

CREATE TABLE IF NOT EXISTS tiering_fact_source (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    fact TEXT NOT NULL,
    source TEXT NOT NULL,
    reference TEXT NOT NULL,
    value TEXT DEFAULT '' NOT NULL,
    as_at DOUBLE PRECISION NOT NULL,
    recorded_by TEXT NOT NULL,
    recorded_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_tiering_fact_source ON tiering_fact_source (model_id, fact, recorded_at);

CREATE TABLE IF NOT EXISTS validation (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    kind TEXT DEFAULT 'initial' NOT NULL,
    scope TEXT DEFAULT '[]' NOT NULL,
    plan TEXT DEFAULT '{}' NOT NULL,
    validators TEXT DEFAULT '[]' NOT NULL,
    independence TEXT DEFAULT '{}' NOT NULL,
    status TEXT DEFAULT 'planned' NOT NULL,
    outcome TEXT,
    conditions TEXT DEFAULT '[]' NOT NULL,
    snapshot_id TEXT,
    tier_at_open INTEGER,
    tier_verdict TEXT,
    tier_note TEXT DEFAULT '' NOT NULL,
    started_at DOUBLE PRECISION NOT NULL,
    completed_at DOUBLE PRECISION,
    due_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS validator_capacity (
    id TEXT NOT NULL,
    validator TEXT NOT NULL,
    episodes_per_quarter DOUBLE PRECISION NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    declared_by TEXT NOT NULL,
    declared_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_validator_capacity ON validator_capacity (validator);

CREATE TABLE IF NOT EXISTS vendor_assessment (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    reference TEXT NOT NULL,
    vendor TEXT NOT NULL,
    product TEXT NOT NULL,
    vendor_version TEXT NOT NULL,
    artifact_digest TEXT,
    kind TEXT NOT NULL,
    state TEXT DEFAULT 'open' NOT NULL,
    customisation TEXT DEFAULT '' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    concluded_at DOUBLE PRECISION,
    concluded_by TEXT,
    conclusion TEXT,
    conclusion_note TEXT DEFAULT '' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_vendor_assessment_model ON vendor_assessment (model_id, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vendor_assessment_reference ON vendor_assessment (reference);

CREATE TABLE IF NOT EXISTS vendor_item (
    id TEXT NOT NULL,
    assessment_id TEXT NOT NULL,
    item TEXT NOT NULL,
    kind TEXT NOT NULL,
    answer TEXT DEFAULT '' NOT NULL,
    evidence TEXT DEFAULT '[]' NOT NULL,
    answered_by TEXT,
    answered_at DOUBLE PRECISION,
    stated_at DOUBLE PRECISION,
    covers_version TEXT,
    state TEXT DEFAULT 'outstanding' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_vendor_item_assessment ON vendor_item (assessment_id, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vendor_item ON vendor_item (assessment_id, item);

CREATE TABLE IF NOT EXISTS version_approval (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    tier INTEGER,
    required_roles TEXT DEFAULT '[]' NOT NULL,
    band TEXT,
    stages TEXT DEFAULT '[]' NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE PRECISION NOT NULL,
    completed_at DOUBLE PRECISION,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_version_approval ON version_approval (model_version_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_version_approval_model_version_id_opened_at ON version_approval (model_version_id, opened_at);

CREATE TABLE IF NOT EXISTS version_approval_signature (
    id TEXT NOT NULL,
    version_approval_id TEXT NOT NULL,
    principal TEXT NOT NULL,
    role TEXT NOT NULL,
    decision TEXT DEFAULT 'approve' NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    signed_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_version_approval_signature_principal ON version_approval_signature (version_approval_id, principal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_version_approval_signature_role ON version_approval_signature (version_approval_id, role);

CREATE TABLE IF NOT EXISTS warrant (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    binding_kind TEXT NOT NULL,
    alias_name TEXT,
    version_id TEXT,
    flavour TEXT NOT NULL,
    principal TEXT NOT NULL,
    declared_use TEXT NOT NULL,
    ttl_seconds INTEGER NOT NULL,
    grace_seconds INTEGER DEFAULT 0 NOT NULL,
    rate_per_minute INTEGER,
    quota INTEGER,
    quota_window_hours DOUBLE PRECISION DEFAULT 24.0 NOT NULL,
    cost_budget DOUBLE PRECISION,
    revoked BOOLEAN DEFAULT false NOT NULL,
    revoke_reason TEXT,
    epoch INTEGER DEFAULT 0 NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_warrant_model ON warrant (model_id);

CREATE TABLE IF NOT EXISTS warrant_invocation (
    id TEXT NOT NULL,
    warrant_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    semver TEXT,
    principal TEXT NOT NULL,
    declared_use TEXT NOT NULL,
    environment TEXT NOT NULL,
    verb TEXT DEFAULT 'score' NOT NULL,
    outcome TEXT NOT NULL,
    refusal_code TEXT,
    latency_ms DOUBLE PRECISION,
    cost DOUBLE PRECISION,
    boundary_ok BOOLEAN,
    request_id TEXT,
    at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_warrant_invocation_model_id_at ON warrant_invocation (model_id, at);
CREATE INDEX IF NOT EXISTS ix_warrant_invocation_warrant_id ON warrant_invocation (warrant_id);

CREATE TABLE IF NOT EXISTS warrant_profile (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    version INTEGER NOT NULL,
    when_facts TEXT DEFAULT '{}' NOT NULL,
    defaults TEXT DEFAULT '{}' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    specificity INTEGER DEFAULT 0 NOT NULL,
    retired BOOLEAN DEFAULT false NOT NULL,
    digest TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    retired_at DOUBLE PRECISION,
    retired_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_warrant_profile ON warrant_profile (retired, specificity);
CREATE UNIQUE INDEX IF NOT EXISTS uq_warrant_profile_name_version ON warrant_profile (name, version);

-- --------------------------------------------------------------------------
-- ENFORCEMENT
--
-- Until these existed, "versions are immutable" was a COMMENT in tables.py and
-- nothing in either dialect stopped a generic UPDATE. Adversarial review 4.5
-- named that: a convention written where a reader expects a constraint.
--
-- Every one of these RAISES. Finding C-3 was raised against a rule that
-- silently discarded the write instead, and design rule E8 is what survived it:
-- silence is never an acceptable enforcement mechanism for an integrity
-- control. A caller that tries to rewrite history is told, with the column
-- named.
-- --------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION maya_immutable_model_version()
RETURNS trigger AS $$
BEGIN
    IF NEW.model_id IS DISTINCT FROM OLD.model_id THEN
        RAISE EXCEPTION 'model_version.model_id is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.semver IS DISTINCT FROM OLD.semver THEN
        RAISE EXCEPTION 'model_version.semver is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.manifest IS DISTINCT FROM OLD.manifest THEN
        RAISE EXCEPTION 'model_version.manifest is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.manifest_digest IS DISTINCT FROM OLD.manifest_digest THEN
        RAISE EXCEPTION 'model_version.manifest_digest is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.trainability_class IS DISTINCT FROM OLD.trainability_class THEN
        RAISE EXCEPTION 'model_version.trainability_class is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.parameter_kind IS DISTINCT FROM OLD.parameter_kind THEN
        RAISE EXCEPTION 'model_version.parameter_kind is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.fit_procedure IS DISTINCT FROM OLD.fit_procedure THEN
        RAISE EXCEPTION 'model_version.fit_procedure is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.deterministic IS DISTINCT FROM OLD.deterministic THEN
        RAISE EXCEPTION 'model_version.deterministic is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.input_schema IS DISTINCT FROM OLD.input_schema THEN
        RAISE EXCEPTION 'model_version.input_schema is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.parameter_schema IS DISTINCT FROM OLD.parameter_schema THEN
        RAISE EXCEPTION 'model_version.parameter_schema is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.output_schema IS DISTINCT FROM OLD.output_schema THEN
        RAISE EXCEPTION 'model_version.output_schema is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.artifact_digest IS DISTINCT FROM OLD.artifact_digest THEN
        RAISE EXCEPTION 'model_version.artifact_digest is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'model_version.created_at is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    IF NEW.created_by IS DISTINCT FROM OLD.created_by THEN
        RAISE EXCEPTION 'model_version.created_by is immutable: it describes what the version IS, and changing it would leave the register describing a model nobody approved. Create a new version';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS immutable_model_version ON model_version;
CREATE TRIGGER immutable_model_version BEFORE UPDATE ON model_version
FOR EACH ROW EXECUTE FUNCTION maya_immutable_model_version();

CREATE OR REPLACE FUNCTION maya_append_only_evidence_node()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'evidence_node is append-only: it is the evidence chain, and a row that can be rewritten or removed is not evidence. Append a correcting node instead';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS append_only_evidence_node ON evidence_node;
CREATE TRIGGER append_only_evidence_node
BEFORE UPDATE OR DELETE ON evidence_node
FOR EACH ROW EXECUTE FUNCTION maya_append_only_evidence_node();

CREATE OR REPLACE FUNCTION maya_empty_when_flagged_evidence_node()
RETURNS trigger AS $$
BEGIN
    IF NEW.contains_personal_data AND coalesce(NEW.payload, '') NOT IN ('', '{}') THEN
        RAISE EXCEPTION 'evidence_node.payload: a node flagged as containing personal data must store an EMPTY payload. The chain cannot be edited, so a node that holds content it may later be asked to erase is a request this register could never honour. Law L-18: the payload is discarded at append, not stored behind a pointer';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS empty_when_flagged_evidence_node ON evidence_node;
CREATE TRIGGER empty_when_flagged_evidence_node
BEFORE INSERT ON evidence_node
FOR EACH ROW EXECUTE FUNCTION maya_empty_when_flagged_evidence_node();
