-- ==========================================================================
-- MAYA — SQLite schema (development default)
-- Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
-- ==========================================================================
--
--                    GENERATED. DO NOT EDIT THIS FILE.
--
-- The schema is db/schema/tables.py, and this is rendered from it by
-- tools/ci/render_schema.py so that it can be read, reviewed or handed to a
-- change-control process without running Python. Edit the Python; re-render.
-- CI fails if the two disagree.
--
-- There are no migrations. Both dialects are applied with CREATE TABLE IF NOT
-- EXISTS, so starting against an existing database is a no-op — which also
-- means an existing table is SKIPPED and a new column never arrives. That is
-- what `run_maya_web.py --check-schema` and `--repair-schema` are for.
--
-- Three column types, one declaration each:
--   TEXT      identifiers, enumerations, and JSON documents held as text
--   INTEGER   counts and sequence numbers
--   BOOLEAN   truth values
--   DOUBLE    epoch-second timestamps and scores
--
-- Timestamps are epoch seconds rather than a date type: MAYA is bitemporal,
-- event_ts and ingest_ts are compared and arithmetic'd throughout, and the
-- same values live in Delta outside this database entirely.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS ai_capability (
    id TEXT NOT NULL,
    capability_key TEXT NOT NULL,
    description TEXT NOT NULL,
    tier TEXT NOT NULL,
    oracle_key TEXT,
    autonomy TEXT DEFAULT 'human_approved_automation' NOT NULL,
    base_model TEXT NOT NULL,
    prompt_digest TEXT NOT NULL,
    review_sample DOUBLE DEFAULT (0.1) NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    owner TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ai_capability_capability_key ON ai_capability (capability_key);

CREATE TABLE IF NOT EXISTS ai_generation (
    id TEXT NOT NULL,
    capability_id TEXT NOT NULL,
    subject_type TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    prompt_digest TEXT NOT NULL,
    base_model TEXT NOT NULL,
    output TEXT DEFAULT '{}' NOT NULL,
    claims TEXT DEFAULT '[]' NOT NULL,
    rejected_claims TEXT DEFAULT '[]' NOT NULL,
    oracle_verdict TEXT DEFAULT '{}' NOT NULL,
    state TEXT DEFAULT 'drafted' NOT NULL,
    sampled BOOLEAN DEFAULT 0 NOT NULL,
    attested_by TEXT,
    attested_at DOUBLE,
    edit_distance DOUBLE,
    created_at DOUBLE NOT NULL,
    created_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_generation_capability ON ai_generation (capability_id, state);

CREATE TABLE IF NOT EXISTS alias (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    name TEXT NOT NULL,
    version_id TEXT NOT NULL,
    moved_at DOUBLE NOT NULL,
    moved_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_alias_model_id_environment_name ON alias (model_id, environment, name);

CREATE TABLE IF NOT EXISTS alias_history (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    name TEXT NOT NULL,
    from_version_id TEXT,
    to_version_id TEXT NOT NULL,
    refinement TEXT DEFAULT '{}' NOT NULL,
    variance TEXT DEFAULT '{}' NOT NULL,
    moved_at DOUBLE NOT NULL,
    moved_by TEXT NOT NULL,
    justification TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_alias_history_model ON alias_history (model_id);

CREATE TABLE IF NOT EXISTS amendment (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    reference TEXT NOT NULL,
    reason TEXT NOT NULL,
    scope TEXT DEFAULT '[]' NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE NOT NULL,
    closed_at DOUBLE,
    closed_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_amendment_model ON amendment (model_id, status);

CREATE TABLE IF NOT EXISTS api_key (
    id TEXT NOT NULL,
    principal_id TEXT NOT NULL,
    username TEXT NOT NULL,
    name TEXT NOT NULL,
    prefix TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    scopes TEXT DEFAULT '[]' NOT NULL,
    created_at DOUBLE NOT NULL,
    created_by TEXT NOT NULL,
    expires_at DOUBLE NOT NULL,
    last_used_at DOUBLE,
    use_count INTEGER DEFAULT 0 NOT NULL,
    revoked_at DOUBLE,
    revoked_by TEXT,
    revoke_reason TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_api_key_key_hash ON api_key (key_hash);
CREATE UNIQUE INDEX IF NOT EXISTS uq_api_key_username_name ON api_key (username, name);

CREATE TABLE IF NOT EXISTS attachment (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    subject_type TEXT DEFAULT 'model_version' NOT NULL,
    subject_id TEXT,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    filename TEXT NOT NULL,
    media_type TEXT DEFAULT 'application/octet-stream' NOT NULL,
    digest TEXT NOT NULL,
    size_bytes INTEGER DEFAULT 0 NOT NULL,
    text_indexed BOOLEAN DEFAULT 0 NOT NULL,
    state TEXT DEFAULT 'attached' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    attached_by TEXT NOT NULL,
    attached_at DOUBLE NOT NULL,
    reviewed_by TEXT,
    reviewed_at DOUBLE,
    review_note TEXT DEFAULT '' NOT NULL,
    supersedes TEXT,
    superseded_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_attachment_model ON attachment (model_id, state);
CREATE INDEX IF NOT EXISTS ix_attachment_version ON attachment (model_version_id, kind);

CREATE TABLE IF NOT EXISTS attestation (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    amendment_id TEXT,
    kind TEXT DEFAULT 'initial' NOT NULL,
    required_roles TEXT DEFAULT '[]' NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE NOT NULL,
    completed_at DOUBLE,
    expires_at DOUBLE,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_attestation_model ON attestation (model_id, status);

CREATE TABLE IF NOT EXISTS attestation_signature (
    id TEXT NOT NULL,
    attestation_id TEXT NOT NULL,
    principal TEXT NOT NULL,
    role TEXT NOT NULL,
    decision TEXT NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    signed_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_signature_attestation ON attestation_signature (attestation_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_signature_attestation_principal ON attestation_signature (attestation_id, principal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_signature_attestation_role ON attestation_signature (attestation_id, role);

CREATE TABLE IF NOT EXISTS baseline_import (
    id TEXT NOT NULL,
    reference TEXT NOT NULL,
    source TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    models INTEGER DEFAULT 0 NOT NULL,
    debt_items INTEGER DEFAULT 0 NOT NULL,
    imported_by TEXT NOT NULL,
    imported_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS board_pack (
    id TEXT NOT NULL,
    period TEXT NOT NULL,
    scope TEXT DEFAULT '{}' NOT NULL,
    as_at DOUBLE NOT NULL,
    models INTEGER DEFAULT 0 NOT NULL,
    indicators TEXT DEFAULT '[]' NOT NULL,
    exceptions TEXT DEFAULT '[]' NOT NULL,
    unmeasured TEXT DEFAULT '{}' NOT NULL,
    digest TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_board_pack_at ON board_pack (as_at);

CREATE TABLE IF NOT EXISTS breach (
    id TEXT NOT NULL,
    monitor_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    observation_id TEXT NOT NULL,
    severity TEXT NOT NULL,
    consecutive INTEGER DEFAULT 1 NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    finding_id TEXT,
    status TEXT DEFAULT 'open' NOT NULL,
    opened_at DOUBLE NOT NULL,
    closed_at DOUBLE,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_breach_model ON breach (model_id, status);

CREATE TABLE IF NOT EXISTS compliance_debt (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    import_id TEXT,
    gap_key TEXT NOT NULL,
    description TEXT NOT NULL,
    materiality TEXT DEFAULT 'Medium' NOT NULL,
    tier INTEGER,
    status TEXT DEFAULT 'open' NOT NULL,
    "plan" TEXT DEFAULT '' NOT NULL,
    owner TEXT NOT NULL,
    finding_id TEXT,
    raised_at DOUBLE NOT NULL,
    expires_at DOUBLE NOT NULL,
    closed_at DOUBLE,
    closed_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_debt_model ON compliance_debt (model_id, status);

CREATE TABLE IF NOT EXISTS dataset_snapshot (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT DEFAULT 'training' NOT NULL,
    delta_table TEXT NOT NULL,
    delta_version BIGINT DEFAULT 0 NOT NULL,
    row_count INTEGER DEFAULT 0 NOT NULL,
    as_of DOUBLE NOT NULL,
    pit_verified BOOLEAN DEFAULT 0 NOT NULL,
    pit_report TEXT DEFAULT '{}' NOT NULL,
    featureset TEXT,
    featureset_version INTEGER,
    digest TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS derived_feature (
    id TEXT NOT NULL,
    feature_id TEXT NOT NULL,
    name TEXT NOT NULL,
    expression TEXT NOT NULL,
    inputs TEXT DEFAULT '[]' NOT NULL,
    evaluator TEXT DEFAULT 'internal' NOT NULL,
    on_error TEXT DEFAULT 'null' NOT NULL,
    definition_version INTEGER DEFAULT 1 NOT NULL,
    digest TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_derived_feature ON derived_feature (feature_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_derived_feature_name_definition_version ON derived_feature (name, definition_version);

CREATE TABLE IF NOT EXISTS document (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    subject_type TEXT DEFAULT 'model_version' NOT NULL,
    subject_id TEXT,
    kind TEXT NOT NULL,
    title TEXT NOT NULL,
    sections TEXT DEFAULT '[]' NOT NULL,
    citations TEXT DEFAULT '[]' NOT NULL,
    coverage TEXT DEFAULT '{}' NOT NULL,
    digest TEXT NOT NULL,
    subjects TEXT DEFAULT '[]' NOT NULL,
    evidence_head INTEGER DEFAULT 0 NOT NULL,
    status TEXT DEFAULT 'compiled' NOT NULL,
    compiled_at DOUBLE NOT NULL,
    compiled_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_document_model ON document (model_id, kind);

CREATE TABLE IF NOT EXISTS evidence_checkpoint (
    id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    chain_hash TEXT NOT NULL,
    verified_at DOUBLE NOT NULL,
    verified_by TEXT DEFAULT 'system' NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS evidence_node (
    id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    kind TEXT NOT NULL,
    subject_type TEXT NOT NULL,
    subject_id TEXT NOT NULL,
    payload TEXT DEFAULT '{}' NOT NULL,
    parents TEXT DEFAULT '[]' NOT NULL,
    contains_personal_data BOOLEAN DEFAULT 0 NOT NULL,
    content_hash TEXT NOT NULL,
    prev_hash TEXT NOT NULL,
    chain_hash TEXT NOT NULL,
    trust DOUBLE DEFAULT (1.0) NOT NULL,
    recorded_at DOUBLE NOT NULL,
    recorded_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_evidence_subject ON evidence_node (subject_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_evidence_node_seq ON evidence_node (seq);

CREATE TABLE IF NOT EXISTS feature (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    entity TEXT NOT NULL,
    dtype TEXT NOT NULL,
    description TEXT NOT NULL,
    business_definition TEXT,
    owner TEXT NOT NULL,
    source_system TEXT,
    sensitivity TEXT DEFAULT 'internal' NOT NULL,
    pii BOOLEAN DEFAULT 0 NOT NULL,
    protected_basis BOOLEAN DEFAULT 0 NOT NULL,
    proxy_risk TEXT DEFAULT 'none' NOT NULL,
    defaults TEXT DEFAULT '{}' NOT NULL,
    shape TEXT DEFAULT '[]' NOT NULL,
    components TEXT DEFAULT '[]' NOT NULL,
    composes TEXT DEFAULT '[]' NOT NULL,
    operations TEXT DEFAULT '[]' NOT NULL,
    definition_version INTEGER DEFAULT 1 NOT NULL,
    sealed_at DOUBLE,
    sealed_by TEXT,
    seal_note TEXT DEFAULT '' NOT NULL,
    ephemeral BOOLEAN DEFAULT 0 NOT NULL,
    expires_at DOUBLE,
    created_by TEXT DEFAULT 'system' NOT NULL,
    certification TEXT DEFAULT 'experimental' NOT NULL,
    created_at DOUBLE NOT NULL,
    retired_at DOUBLE,
    retired_by TEXT,
    retire_reason TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_feature_entity ON feature (entity);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_name ON feature (name);

CREATE TABLE IF NOT EXISTS feature_contract (
    id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    digest TEXT NOT NULL,
    items TEXT DEFAULT '[]' NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_contract_model_version_id ON feature_contract (model_version_id);

CREATE TABLE IF NOT EXISTS feature_source (
    id TEXT NOT NULL,
    view_name TEXT NOT NULL,
    kind TEXT NOT NULL,
    locator TEXT NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    format TEXT DEFAULT '' NOT NULL,
    options TEXT DEFAULT '{}' NOT NULL,
    credential_ref TEXT,
    enabled BOOLEAN DEFAULT 1 NOT NULL,
    last_pulled_at DOUBLE,
    last_pull_rows INTEGER,
    last_pull_digest TEXT,
    last_pull_detail TEXT DEFAULT '' NOT NULL,
    last_pull_version INTEGER,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    retired_at DOUBLE,
    retired_by TEXT,
    retire_reason TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_feature_source_kind ON feature_source (kind);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_source_view ON feature_source (view_name);

CREATE TABLE IF NOT EXISTS feature_view (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    entity TEXT NOT NULL,
    owner TEXT NOT NULL,
    description TEXT,
    delta_table TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_view_name ON feature_view (name);

CREATE TABLE IF NOT EXISTS feature_view_version (
    id TEXT NOT NULL,
    feature_view_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    features TEXT DEFAULT '[]' NOT NULL,
    delta_version BIGINT DEFAULT 0 NOT NULL,
    valid_time_column TEXT DEFAULT 'event_ts' NOT NULL,
    ingest_time_column TEXT DEFAULT 'ingest_ts' NOT NULL,
    row_count INTEGER DEFAULT 0 NOT NULL,
    quality_report TEXT DEFAULT '{}' NOT NULL,
    materialised_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_fvv_view ON feature_view_version (feature_view_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_feature_view_version_feature_view_id_version ON feature_view_version (feature_view_id, version);

CREATE TABLE IF NOT EXISTS featureset (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    entity TEXT NOT NULL,
    owner TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    slots TEXT DEFAULT '{}' NOT NULL,
    label_slot TEXT,
    outcome_window_days INTEGER DEFAULT 0 NOT NULL,
    defaults TEXT DEFAULT '{}' NOT NULL,
    composes TEXT DEFAULT '[]' NOT NULL,
    operations TEXT DEFAULT '[]' NOT NULL,
    definition_version INTEGER DEFAULT 1 NOT NULL,
    sealed_at DOUBLE,
    sealed_by TEXT,
    seal_note TEXT DEFAULT '' NOT NULL,
    ephemeral BOOLEAN DEFAULT 0 NOT NULL,
    expires_at DOUBLE,
    grain TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    retired_at DOUBLE,
    retired_by TEXT,
    retire_reason TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_featureset_name ON featureset (name);

CREATE TABLE IF NOT EXISTS featureset_version (
    id TEXT NOT NULL,
    featureset_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    bindings TEXT DEFAULT '{}' NOT NULL,
    label_binding TEXT DEFAULT '{}' NOT NULL,
    digest TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_fsv_set ON featureset_version (featureset_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_featureset_version_featureset_id_version ON featureset_version (featureset_id, version);

CREATE TABLE IF NOT EXISTS finding (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    validation_id TEXT,
    source TEXT DEFAULT 'validation' NOT NULL,
    severity TEXT NOT NULL,
    category TEXT DEFAULT 'general' NOT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    affected_component TEXT,
    blocking BOOLEAN DEFAULT 0 NOT NULL,
    owner TEXT NOT NULL,
    raised_at DOUBLE NOT NULL,
    due_at DOUBLE NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    closed_at DOUBLE,
    closure_verified_by TEXT,
    closure_evidence TEXT DEFAULT '{}' NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_finding_open ON finding (model_id, status, severity);

CREATE TABLE IF NOT EXISTS finding_action (
    id TEXT NOT NULL,
    finding_id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    act TEXT NOT NULL,
    actor TEXT NOT NULL,
    from_owner TEXT,
    to_owner TEXT,
    reason TEXT DEFAULT '' NOT NULL,
    "plan" TEXT DEFAULT '' NOT NULL,
    committed_at DOUBLE,
    due_before DOUBLE,
    due_after DOUBLE,
    acted_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_finding_action ON finding_action (finding_id, acted_at);

CREATE TABLE IF NOT EXISTS model (
    id TEXT NOT NULL,
    urn TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    model_class TEXT NOT NULL,
    domain TEXT NOT NULL,
    owner TEXT NOT NULL,
    legal_entity TEXT NOT NULL,
    purpose TEXT NOT NULL,
    origin TEXT DEFAULT 'internal' NOT NULL,
    status TEXT DEFAULT 'draft' NOT NULL,
    tier INTEGER,
    attributes TEXT DEFAULT '{}' NOT NULL,
    created_at DOUBLE NOT NULL,
    created_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_model_domain ON model (domain);
CREATE INDEX IF NOT EXISTS ix_model_tier ON model (tier);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_urn ON model (urn);

CREATE TABLE IF NOT EXISTS model_edge (
    id TEXT NOT NULL,
    from_model TEXT NOT NULL,
    to_model TEXT NOT NULL,
    kind TEXT NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    type_checked BOOLEAN DEFAULT 0 NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_edge_from ON model_edge (from_model);
CREATE INDEX IF NOT EXISTS ix_edge_to ON model_edge (to_model);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_edge_from_model_to_model_kind ON model_edge (from_model, to_model, kind);

CREATE TABLE IF NOT EXISTS model_limitation (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    reference TEXT NOT NULL,
    kind TEXT NOT NULL,
    statement TEXT NOT NULL,
    bound_key TEXT,
    basis TEXT DEFAULT '' NOT NULL,
    raised_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    withdrawn_at DOUBLE,
    withdrawn_by TEXT,
    withdrawal_reason TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_limitation_model_version_id_reference ON model_limitation (model_version_id, reference);

CREATE TABLE IF NOT EXISTS model_version (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    semver TEXT NOT NULL,
    manifest TEXT NOT NULL,
    manifest_digest TEXT NOT NULL,
    trainability_class TEXT NOT NULL,
    parameter_kind TEXT NOT NULL,
    fit_procedure TEXT NOT NULL,
    deterministic BOOLEAN DEFAULT 1 NOT NULL,
    input_schema TEXT DEFAULT '[]' NOT NULL,
    parameter_schema TEXT DEFAULT '[]' NOT NULL,
    output_schema TEXT DEFAULT '[]' NOT NULL,
    contract TEXT DEFAULT '{}' NOT NULL,
    artifact_digest TEXT,
    artifact_uri TEXT,
    artifact_size INTEGER,
    status TEXT DEFAULT 'draft' NOT NULL,
    created_at DOUBLE NOT NULL,
    created_by TEXT NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_version_model ON model_version (model_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_model_version_model_id_semver ON model_version (model_id, semver);

CREATE TABLE IF NOT EXISTS monitor (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,
    test_key TEXT NOT NULL,
    threshold TEXT DEFAULT '{}' NOT NULL,
    slice TEXT DEFAULT '{}' NOT NULL,
    reference TEXT DEFAULT '{}' NOT NULL,
    cadence_days DOUBLE DEFAULT (1.0) NOT NULL,
    label_delay_days DOUBLE DEFAULT (0.0) NOT NULL,
    breach_severity TEXT DEFAULT 'Medium' NOT NULL,
    escalate_after INTEGER DEFAULT 3 NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    owner TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    last_evaluated_at DOUBLE,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_monitor_model ON monitor (model_id, status);

CREATE TABLE IF NOT EXISTS notification (
    id TEXT NOT NULL,
    principal TEXT NOT NULL,
    channel TEXT NOT NULL,
    state TEXT NOT NULL,
    digest TEXT NOT NULL,
    item_count INTEGER DEFAULT 0 NOT NULL,
    overdue INTEGER DEFAULT 0 NOT NULL,
    summary TEXT DEFAULT '' NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    sent_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_notification_principal ON notification (principal);

CREATE TABLE IF NOT EXISTS observation (
    id TEXT NOT NULL,
    monitor_id TEXT NOT NULL,
    value DOUBLE,
    passed BOOLEAN DEFAULT 0 NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    sample_size INTEGER DEFAULT 0 NOT NULL,
    window_start DOUBLE,
    window_end DOUBLE,
    matured BOOLEAN DEFAULT 1 NOT NULL,
    digest TEXT NOT NULL,
    computed_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_observation_monitor ON observation (monitor_id, computed_at);

CREATE TABLE IF NOT EXISTS overlay (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT,
    reference TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,
    direction TEXT DEFAULT 'increase' NOT NULL,
    rationale TEXT NOT NULL,
    basis TEXT DEFAULT '{}' NOT NULL,
    owner TEXT NOT NULL,
    proposed_by TEXT NOT NULL,
    approved_by TEXT,
    status TEXT DEFAULT 'proposed' NOT NULL,
    effective_from DOUBLE,
    expires_at DOUBLE,
    renewals INTEGER DEFAULT 0 NOT NULL,
    finding_id TEXT,
    created_at DOUBLE NOT NULL,
    closed_at DOUBLE,
    closure_reason TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_overlay_model ON overlay (model_id, status);

CREATE TABLE IF NOT EXISTS overlay_measurement (
    id TEXT NOT NULL,
    overlay_id TEXT NOT NULL,
    period TEXT NOT NULL,
    base_value DOUBLE NOT NULL,
    adjusted_value DOUBLE NOT NULL,
    magnitude DOUBLE NOT NULL,
    pct_of_base DOUBLE,
    measured_by TEXT NOT NULL,
    measured_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_measurement_overlay ON overlay_measurement (overlay_id, period);

CREATE TABLE IF NOT EXISTS parameter_set (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    name TEXT NOT NULL,
    version INTEGER DEFAULT 1 NOT NULL,
    kind TEXT NOT NULL,
    provenance TEXT NOT NULL,
    values_inline TEXT DEFAULT '{}' NOT NULL,
    values_uri TEXT,
    cardinality INTEGER DEFAULT 0 NOT NULL,
    diagnostics TEXT DEFAULT '{}' NOT NULL,
    featureset_version_id TEXT,
    window_from DOUBLE,
    window_to DOUBLE,
    as_of DOUBLE,
    snapshot_id TEXT,
    warrant_id TEXT,
    digest TEXT NOT NULL,
    state TEXT DEFAULT 'proposed' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    approved_by TEXT,
    approved_at DOUBLE,
    review_note TEXT DEFAULT '' NOT NULL,
    superseded_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_parameter_set_version ON parameter_set (model_version_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_parameter_set_model_version_id_name_version ON parameter_set (model_version_id, name, version);

CREATE TABLE IF NOT EXISTS policy_rule (
    id TEXT NOT NULL,
    gate TEXT NOT NULL,
    version INTEGER NOT NULL,
    rule TEXT NOT NULL,
    reason TEXT NOT NULL,
    cases TEXT DEFAULT '[]' NOT NULL,
    facts_read TEXT DEFAULT '[]' NOT NULL,
    test_report TEXT DEFAULT '{}' NOT NULL,
    state TEXT DEFAULT 'draft' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    digest TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    published_at DOUBLE,
    published_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_policy_gate ON policy_rule (gate, state);
CREATE UNIQUE INDEX IF NOT EXISTS uq_policy_rule_gate_version ON policy_rule (gate, version);

CREATE TABLE IF NOT EXISTS principal (
    id TEXT NOT NULL,
    username TEXT NOT NULL,
    display_name TEXT NOT NULL,
    kind TEXT DEFAULT 'person' NOT NULL,
    email TEXT,
    roles TEXT DEFAULT '[]' NOT NULL,
    legal_entities TEXT DEFAULT '[]' NOT NULL,
    domains TEXT DEFAULT '[]' NOT NULL,
    status TEXT DEFAULT 'active' NOT NULL,
    password_hash TEXT,
    password_salt TEXT,
    sso_issuer TEXT,
    sso_subject TEXT,
    created_at DOUBLE NOT NULL,
    last_seen_at DOUBLE,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_principal_status ON principal (status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_principal_username ON principal (username);

CREATE TABLE IF NOT EXISTS risk_appetite (
    id TEXT NOT NULL,
    metric TEXT NOT NULL,
    scope_key TEXT DEFAULT '*' NOT NULL,
    scope TEXT DEFAULT '{}' NOT NULL,
    version INTEGER NOT NULL,
    limit_value DOUBLE NOT NULL,
    amber_value DOUBLE,
    direction TEXT NOT NULL,
    unit TEXT NOT NULL,
    rationale TEXT NOT NULL,
    owner TEXT DEFAULT '' NOT NULL,
    review_at DOUBLE,
    retired BOOLEAN DEFAULT 0 NOT NULL,
    digest TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    retired_at DOUBLE,
    retired_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_appetite_metric ON risk_appetite (metric, retired);
CREATE UNIQUE INDEX IF NOT EXISTS uq_risk_appetite_metric_scope_key_version ON risk_appetite (metric, scope_key, version);

CREATE TABLE IF NOT EXISTS risk_assessment (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    tier INTEGER NOT NULL,
    materiality TEXT NOT NULL,
    complexity TEXT NOT NULL,
    facts TEXT DEFAULT '{}' NOT NULL,
    required_controls TEXT DEFAULT '[]' NOT NULL,
    rationale TEXT NOT NULL,
    ruleset_version TEXT NOT NULL,
    next_review_due DOUBLE,
    assessed_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_risk_model ON risk_assessment (model_id);

CREATE TABLE IF NOT EXISTS role (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    permissions TEXT DEFAULT '[]' NOT NULL,
    built_in BOOLEAN DEFAULT 0 NOT NULL,
    created_at DOUBLE NOT NULL,
    created_by TEXT DEFAULT 'system' NOT NULL,
    updated_at DOUBLE,
    updated_by TEXT,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_role_name ON role (name);

CREATE TABLE IF NOT EXISTS scheduled_run (
    id TEXT NOT NULL,
    job TEXT NOT NULL,
    outcome TEXT DEFAULT '{}' NOT NULL,
    ok BOOLEAN DEFAULT 1 NOT NULL,
    error TEXT,
    duration_ms DOUBLE DEFAULT 0 NOT NULL,
    ran_by TEXT NOT NULL,
    ran_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_scheduled_run_job ON scheduled_run (job, ran_at);

CREATE TABLE IF NOT EXISTS serving_attestation (
    id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    warrant_id TEXT,
    descriptor_id TEXT,
    served TEXT DEFAULT '{}' NOT NULL,
    pinned TEXT DEFAULT '{}' NOT NULL,
    agrees BOOLEAN DEFAULT 0 NOT NULL,
    divergence TEXT DEFAULT '[]' NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    attested_by TEXT NOT NULL,
    attested_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_serving_version ON serving_attestation (model_version_id);

CREATE TABLE IF NOT EXISTS telemetry_batch (
    id TEXT NOT NULL,
    digest TEXT NOT NULL,
    delta_table TEXT NOT NULL,
    row_count INTEGER DEFAULT 0 NOT NULL,
    at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_telemetry_batch_digest ON telemetry_batch (digest);

CREATE TABLE IF NOT EXISTS test_result (
    id TEXT NOT NULL,
    validation_id TEXT NOT NULL,
    test_key TEXT NOT NULL,
    parameters TEXT DEFAULT '{}' NOT NULL,
    slice TEXT DEFAULT '{}' NOT NULL,
    value DOUBLE,
    threshold TEXT DEFAULT '{}' NOT NULL,
    passed BOOLEAN DEFAULT 0 NOT NULL,
    detail TEXT DEFAULT '' NOT NULL,
    digest TEXT NOT NULL,
    computed_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_test_result_validation ON test_result (validation_id, test_key);

CREATE TABLE IF NOT EXISTS validation (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    kind TEXT DEFAULT 'initial' NOT NULL,
    scope TEXT DEFAULT '[]' NOT NULL,
    "plan" TEXT DEFAULT '{}' NOT NULL,
    validators TEXT DEFAULT '[]' NOT NULL,
    independence TEXT DEFAULT '{}' NOT NULL,
    status TEXT DEFAULT 'planned' NOT NULL,
    outcome TEXT,
    conditions TEXT DEFAULT '[]' NOT NULL,
    snapshot_id TEXT,
    started_at DOUBLE NOT NULL,
    completed_at DOUBLE,
    due_at DOUBLE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS version_approval (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    model_version_id TEXT NOT NULL,
    tier INTEGER,
    required_roles TEXT DEFAULT '[]' NOT NULL,
    status TEXT DEFAULT 'open' NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    opened_by TEXT NOT NULL,
    opened_at DOUBLE NOT NULL,
    completed_at DOUBLE,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_version_approval ON version_approval (model_version_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_version_approval_model_version_id_opened_at ON version_approval (model_version_id, opened_at);

CREATE TABLE IF NOT EXISTS version_approval_signature (
    id TEXT NOT NULL,
    version_approval_id TEXT NOT NULL,
    principal TEXT NOT NULL,
    role TEXT NOT NULL,
    decision TEXT DEFAULT 'approve' NOT NULL,
    statement TEXT DEFAULT '' NOT NULL,
    signed_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_version_approval_signature_principal ON version_approval_signature (version_approval_id, principal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_version_approval_signature_role ON version_approval_signature (version_approval_id, role);

CREATE TABLE IF NOT EXISTS warrant (
    id TEXT NOT NULL,
    model_id TEXT NOT NULL,
    environment TEXT NOT NULL,
    binding_kind TEXT NOT NULL,
    alias_name TEXT,
    version_id TEXT,
    flavour TEXT NOT NULL,
    principal TEXT NOT NULL,
    declared_use TEXT NOT NULL,
    ttl_seconds INTEGER NOT NULL,
    grace_seconds INTEGER DEFAULT 0 NOT NULL,
    revoked BOOLEAN DEFAULT 0 NOT NULL,
    revoke_reason TEXT,
    epoch INTEGER DEFAULT 0 NOT NULL,
    created_at DOUBLE NOT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_warrant_model ON warrant (model_id);

CREATE TABLE IF NOT EXISTS warrant_profile (
    id TEXT NOT NULL,
    name TEXT NOT NULL,
    version INTEGER NOT NULL,
    when_facts TEXT DEFAULT '{}' NOT NULL,
    defaults TEXT DEFAULT '{}' NOT NULL,
    note TEXT DEFAULT '' NOT NULL,
    specificity INTEGER DEFAULT 0 NOT NULL,
    retired BOOLEAN DEFAULT 0 NOT NULL,
    digest TEXT NOT NULL,
    created_by TEXT NOT NULL,
    created_at DOUBLE NOT NULL,
    retired_at DOUBLE,
    retired_by TEXT,
    PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS ix_warrant_profile ON warrant_profile (retired, specificity);
CREATE UNIQUE INDEX IF NOT EXISTS uq_warrant_profile_name_version ON warrant_profile (name, version);
