# ============================================================ CH 22
_state["chapter"] = "22 · Interfaces and the SDK"

sl, y = content("API conventions — and which of them exist",
                "Interfaces · the contract")
data = [["Concern", "Today", "Why, or why not yet"],
        ["Base path", "/api/v1, defined once in routes/base.py::API", "One versioned contract; the interface has no privileged path"],
        ["Spec", "OpenAPI, generated by FastAPI at /api/v1/openapi.json", "Generated from the routes, so it cannot describe a surface that is not there"],
        ["Authentication", "Session cookie for the interface; HTTP Basic against the same principal register for services", "One identity store, not two"],
        ["CSRF", "A token on any state-changing method whose authority came from the cookie, enforced in middleware", "152 mutating endpoints is 126 chances to forget one"],
        ["Refusals", "error / detail / remediation at the top level, 312 codes mapped onto 14 statuses in ONE table", "DR-6 and DR-7 — blocking must always explain"],
        ["Pagination", "?limit= and ?offset=, applied AFTER scope filtering", "Page two of a filtered list must not be page two of the unfiltered one with holes in it"],
        ["Time travel", "?as_of= on the feature and warrant surfaces", "Examiner questions about a past date"],
        ["NOT BUILT", "ETag / If-Match · Idempotency-Key · ?expand= · ?fields= · keyset cursors · SSE on /events · Sunset headers · /derivations/{id}", "Each is designed in docs/14 §27 and none of it runs. Listings return whole; a retry is not idempotent"]]
th = table(sl, data, ML, y, CW, col_w=[1.5, 5.4, 4.7], row_h=0.30, fs=9.5, hfs=10,
           bold_col0=True, first_col_color=CRIMSON)
tf = txt(sl, ML, y + th + 0.20, CW, 0.60)
runs(tf, [("One surface, and the interface reaches it the way anybody else does. ", CRIMSON, True),
          ("Models · versions · aliases · risk · features · runs · validation · overlays · monitoring · "
           "warrants · documents · policy · assistance · admin — all behind /api/v1, in one FastAPI "
           "process that also renders the pages. The two-process, generated-client front end is an "
           "accepted design and is not built.", INK, False)],
     size=10.5, first=True, space_after=0, line=1.24)

sl, y = content("Single sign-on — and the part of it that is not mechanical",
                "Interfaces · identity")
tf = txt(sl, ML, y, CW * 0.52, 0.35)
para(tf, "The mechanical half", size=12.5, color=INK, bold=True, font=SERIF, first=True, space_after=0)
h = code(sl, ML, y + 0.40, CW * 0.52, [
 "# authorisation code + PKCE + state + nonce",
 "recovered = pow(sig, e, n)",
 "expected  = b\"\\x00\\x01\" + b\"\\xff\" * pad + b\"\\x00\" \\",
 "          + SHA256_DIGEST_INFO + digest",
 "return hmac.compare_digest(recovered, expected)",
 "",
 "# and the algorithm is DECIDED, never read:",
 "if header[\"alg\"] != \"RS256\": raise unsupported",
], fs=9, title="core/authz/jws.py — standard library only")
tf = txt(sl, ML, y + 0.40 + h + 0.24, CW * 0.52, 1.5)
runs(tf, [("Standard library only, so MAYA deploys air-gapped. ", CRIMSON, True),
          ("The padded block is CONSTRUCTED and compared rather than parsed, and the algorithm is "
           "decided rather than read from the token — the two ways signature verification is "
           "classically defeated.", INK, False)],
     size=10.5, first=True, space_after=0, line=1.26)
x = ML + CW * 0.56
tf = txt(sl, x, y, CW * 0.44, 0.35)
para(tf, "The half that is not", size=12.5, color=CRIMSON, bold=True, font=SERIF, first=True, space_after=0)
tf = txt(sl, x, y + 0.42, CW * 0.44, 1.15)
runs(tf, [("An identity provider that grants MAYA roles is one that ", INK, False),
          ("decides segregation of duties", CRIMSON, True),
          (" — and the person administering it is very often the person whose duties are being segregated.",
           INK, False)], size=11.5, first=True, space_after=0, line=1.26)
data = [["Rule", "Because"],
        ["Groups are MAPPED, never obeyed",
         "An unmapped group grants nothing"],
        ["Identity binds to (issuer, subject)",
         "A username is not an identity: claiming to be called admin once made you one"],
        ["Incompatible roles refuse the LOGIN",
         "Checked before provisioning, so the lesser problem cannot hide the greater"],
        ["Issuer, subject and groups recorded",
         "“Why did they hold that role in March” survives the directory moving on"]]
# row_h is a FLOOR, not a height: theme.table() adds padding plus one text line
# on top of it, so a generous floor makes every row taller than its content and
# the table taller than its slide. Let the content decide.
th = table(sl, data, x, y + 1.55, CW * 0.44, col_w=[2.2, 3.1], row_h=0.34, fs=8.5, hfs=9,
           bold_col0=True, first_col_color=CRIMSON)
cy = y + 1.55 + th + 0.20
rect(sl, ML, cy, CW, 0.62, fill=PARCH)
rect(sl, ML, cy, 0.045, 0.62, fill=CRIMSON)
tf = txt(sl, ML + 0.30, cy + 0.10, CW - 0.6, 0.50)
runs(tf, [("No SAML and no SCIM. ", CRIMSON, True),
          ("OIDC is supported; a SAML-only directory and automatic deprovisioning are not, so ", INK, False),
          ("a leaver is suspended by hand", INK, True),
          (" — which is an operational obligation worth stating here rather than discovering in an access review.", INK, False)],
     size=11, first=True, space_after=0, line=1.24)

sl, y = content("Front end and SDK", "Interfaces · clients")
tf = txt(sl, ML, y, CW * 0.47, 0.35)
para(tf, "The interface — one process, not two", size=12.5, color=INK, bold=True, font=SERIF, first=True, space_after=0)
data = [["Concern", "Today"],
        ["Process", "One FastAPI application serves /api/v1 and renders the pages. The decoupled two-origin front end is ADR-011, accepted and not built — there is no CORS middleware anywhere"],
        ["Auth", "Session cookie, SameSite=Strict, plus a CSRF token on cookie-authorised mutations"],
        ["Logic", "The server renders decisions; the page never derives them"],
        ["Client", "The Python SDK is hand-written against the same /api/v1. There is no generated client and no openapi.lock.json, so nothing detects spec drift — CI runs the suite, not a contract check"],
        ["Documents", "Compiled server-side to markdown and rendered through the help pipeline; PDF and DOCX are not built"],
        ["Legibility", "Theme and a five-step text scale, both applied before the first paint. 31 assertions hold WCAG AA contrast in both themes, a focus ring on every focusable kind, and no template pinning a colour or a pixel size"]]
table(sl, data, ML, y + 0.40, CW * 0.47, col_w=[1.1, 4.6], row_h=0.30, fs=9, hfs=10, bold_col0=True, first_col_color=CRIMSON)
x = ML + CW * 0.53
tf = txt(sl, x, y, CW * 0.47, 0.35)
para(tf, "SDK — the compliant path must be the shortest", size=12.5, color=INK, bold=True, font=SERIF, first=True, space_after=0)
tf = txt(sl, x, y + 0.42, CW * 0.47, 2.0)
bullets(tf, ["resolve() returns the descriptor; execute() sends the inputs and never hands the caller one to keep",
             "It deliberately does NOT re-validate a warrant — a second check could only disagree with the first, on a stale copy of the vocabulary",
             "Expiry is on the document where a caller can read it, because a client that caches one has turned a revocable authorisation into a permanent one",
             "The boundary check, the local revocation list and the signature check are in the captive engine (core/execution/engine.py), not in this client"],
        size=10, gap=6)
rect(sl, x, y + 2.35, CW * 0.47, 1.35, fill=PARCH)
rect(sl, x, y + 2.35, 0.045, 1.35, fill=CRIMSON)
tf = txt(sl, x + 0.26, y + 2.49, CW * 0.47 - 0.5, 1.1)
runs(tf, [("The design point. ", CRIMSON, True),
          ("A developer who uses the SDK gets governance for free and cannot forget a step. If the compliant path is slower than "
           "the non-compliant one, the inventory rots. Python ships; the Java SDK is a written contract in sdk/java/README.md "
           "and no implementation.", INK, False)],
     size=11, first=True, space_after=0, line=1.26)
