"""
MAYA — write db/schema/{sqlite,postgres}.sql from the typed metadata.
Copyright © 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.

The schema is `db/schema/tables.py`. These two files are GENERATED REFERENCE:
a DBA reviewing what MAYA will create, or a DDL to hand to a change-control
process, without reading Python or running the application.

They were once the schema itself, hand-maintained in parallel, with a test that
compared them. That test could only ever report a divergence somebody had
already shipped — and it did, more than once. One declaration cannot diverge
from itself.

    python tools/ci/render_schema.py          # rewrite both files
    python tools/ci/render_schema.py --check  # fail if they are stale

`--check` runs in CI, so a change to `tables.py` that does not regenerate these
is caught before it turns them into fiction.
"""
from __future__ import annotations

import pathlib
import sys

from sqlalchemy.dialects import postgresql, sqlite
from sqlalchemy.schema import CreateIndex, CreateTable

ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from db.schema.tables import METADATA

HEADER = """\
-- ==========================================================================
-- MAYA — {title}
-- Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
-- ==========================================================================
--
--                    GENERATED. DO NOT EDIT THIS FILE.
--
-- The schema is db/schema/tables.py, and this is rendered from it by
-- tools/ci/render_schema.py so that it can be read, reviewed or handed to a
-- change-control process without running Python. Edit the Python; re-render.
-- CI fails if the two disagree.
--
-- There are no migrations. Both dialects are applied with CREATE TABLE IF NOT
-- EXISTS, so starting against an existing database is a no-op — which also
-- means an existing table is SKIPPED and a new column never arrives. That is
-- what `run_maya_web.py --check-schema` and `--repair-schema` are for.
--
-- Three column types, one declaration each:
--   TEXT      identifiers, enumerations, and JSON documents held as text
--   INTEGER   counts and sequence numbers
--   BOOLEAN   truth values
--   {double:<9} epoch-second timestamps and scores
--
-- Timestamps are epoch seconds rather than a date type: MAYA is bitemporal,
-- event_ts and ingest_ts are compared and arithmetic'd throughout, and the
-- same values live in Delta outside this database entirely.
-- ==========================================================================

"""

DIALECTS = {
    "sqlite.sql": (sqlite.dialect(), "SQLite schema (development default)", "DOUBLE"),
    "postgres.sql": (postgresql.dialect(), "PostgreSQL schema", "DOUBLE PRECISION"),
}


def _tidy(ddl: str) -> str:
    """Spaces, not tabs, and no trailing whitespace.

    SQLAlchemy indents with a tab and leaves a space after every comma. Fine
    for a statement about to be executed, and this file exists to be READ."""
    return "\n".join(line.replace("\t", "    ").rstrip()
                     for line in ddl.splitlines())


def render(dialect) -> str:
    out = []
    for name in sorted(METADATA.tables):
        table = METADATA.tables[name]
        ddl = str(CreateTable(table, if_not_exists=True).compile(dialect=dialect))
        out.append(_tidy(ddl).strip().rstrip(";") + ";")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            statement = str(CreateIndex(index, if_not_exists=True)
                            .compile(dialect=dialect))
            out.append(_tidy(statement).strip().rstrip(";") + ";")
        out.append("")
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for filename, (dialect, title, double) in DIALECTS.items():
        path = ROOT / "db" / "schema" / filename
        body = HEADER.format(title=title, double=double) + render(dialect)
        if check:
            if not path.is_file() or path.read_text() != body:
                stale.append(filename)
        else:
            path.write_text(body)
            print(f"wrote {path.relative_to(ROOT)}  "
                  f"({len(body.splitlines())} lines)")
    if stale:
        print("these generated files no longer match db/schema/tables.py: "
              + ", ".join(stale))
        print("run: python tools/ci/render_schema.py")
        return 1
    if check:
        print("db/schema/*.sql match db/schema/tables.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
